function status = runsimulationstep(obj,id,istepnum)
%runsimulationstep(obj,id,istepnum)
%
%   Service definition of function ns__runsimulationstep
%   
%     Input:
%       id = (int)
%       istepnum = (int)
%   
%     Output:
%       status = (int)

% Build up the argument lists.
values = { ...
   id, ...
   istepnum, ...
   };
names = { ...
   'id', ...
   'istepnum', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'runsimulationstep', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
status = parseSoapResponse(response);
