##################################################
# file: IoSteerWS_types.py
#
# schema types generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#    C:\Python25\Scripts\wsdl2py-script.py ..\..\IoSimulation\IoSteerWS.wsdl
#
##################################################

import ZSI
import ZSI.TCcompound
from ZSI.schema import LocalElementDeclaration, ElementDeclaration, TypeDefinition, GTD, GED

##############################
# targetNamespace
# urn:IoSteerWS
##############################

class ns0:
    targetNamespace = "urn:IoSteerWS"

    class ArrayOfdouble_Def(ZSI.TC.Array, TypeDefinition):
        #complexType/complexContent base="SOAP-ENC:Array"
        schema = "urn:IoSteerWS"
        type = (schema, "ArrayOfdouble")
        def __init__(self, pname, ofwhat=(), extend=False, restrict=False, attributes=None, **kw):
            ofwhat = ZSI.TCnumbers.FPdouble(None, typed=False)
            atype = (u'http://www.w3.org/2001/XMLSchema', u'double[]')
            ZSI.TCcompound.Array.__init__(self, atype, ofwhat, pname=pname, childnames='item', **kw)

# end class ns0 (tns: urn:IoSteerWS)
