/* soapServer.cpp
   Generated by gSOAP 2.7.6e from IoSteerWS.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.7.6e 2009-09-16 07:33:26 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (!--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:add"))
		return soap_serve_ns__add(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getstep"))
		return soap_serve_ns__getstep(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setstep"))
		return soap_serve_ns__setstep(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getnsteps"))
		return soap_serve_ns__getnsteps(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setnsteps"))
		return soap_serve_ns__setnsteps(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:runsimulationstep"))
		return soap_serve_ns__runsimulationstep(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:runsimulation"))
		return soap_serve_ns__runsimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:requestsimulation"))
		return soap_serve_ns__requestsimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:runrequestedsimulation"))
		return soap_serve_ns__runrequestedsimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:submitsimulation"))
		return soap_serve_ns__submitsimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:simulationstatus"))
		return soap_serve_ns__simulationstatus(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setsimulationstatus"))
		return soap_serve_ns__setsimulationstatus(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getsimulationresults"))
		return soap_serve_ns__getsimulationresults(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:deletesimulation"))
		return soap_serve_ns__deletesimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:newsimulation"))
		return soap_serve_ns__newsimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:createsimulation"))
		return soap_serve_ns__createsimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:writelocalsimulation"))
		return soap_serve_ns__writelocalsimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:readlocalsimulation"))
		return soap_serve_ns__readlocalsimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:writesimulation"))
		return soap_serve_ns__writesimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:readsimulation"))
		return soap_serve_ns__readsimulation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:exitiome"))
		return soap_serve_ns__exitiome(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:addparamdouble"))
		return soap_serve_ns__addparamdouble(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:addparamint"))
		return soap_serve_ns__addparamint(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:addparamvec"))
		return soap_serve_ns__addparamvec(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:addparammat"))
		return soap_serve_ns__addparammat(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:addparamstring"))
		return soap_serve_ns__addparamstring(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:addparammmat3d"))
		return soap_serve_ns__addparammmat3d(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:addmetadata"))
		return soap_serve_ns__addmetadata(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getparamdouble"))
		return soap_serve_ns__getparamdouble(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getparamint"))
		return soap_serve_ns__getparamint(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getparamvec"))
		return soap_serve_ns__getparamvec(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getparammat"))
		return soap_serve_ns__getparammat(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getparamstring"))
		return soap_serve_ns__getparamstring(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getparammmat3d"))
		return soap_serve_ns__getparammmat3d(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getmetadata"))
		return soap_serve_ns__getmetadata(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setparamdouble"))
		return soap_serve_ns__setparamdouble(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setparamint"))
		return soap_serve_ns__setparamint(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setparamvec"))
		return soap_serve_ns__setparamvec(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setparammat"))
		return soap_serve_ns__setparammat(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setparamstring"))
		return soap_serve_ns__setparamstring(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setparammmat3d"))
		return soap_serve_ns__setparammmat3d(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setmetadata"))
		return soap_serve_ns__setmetadata(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:listmetadata"))
		return soap_serve_ns__listmetadata(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:deletemetadata"))
		return soap_serve_ns__deletemetadata(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:deleteparam"))
		return soap_serve_ns__deleteparam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:listparam"))
		return soap_serve_ns__listparam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getnumobj"))
		return soap_serve_ns__getnumobj(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getobjnum"))
		return soap_serve_ns__getobjnum(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:testgroupbarrier"))
		return soap_serve_ns__testgroupbarrier(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:setgroupbarrier"))
		return soap_serve_ns__setgroupbarrier(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__add(struct soap *soap)
{	struct ns__add soap_tmp_ns__add;
	struct ns__addResponse soap_tmp_ns__addResponse;
	double soap_tmp_double;
	soap_default_ns__addResponse(soap, &soap_tmp_ns__addResponse);
	soap_default_double(soap, &soap_tmp_double);
	soap_tmp_ns__addResponse.result = &soap_tmp_double;
	soap_default_ns__add(soap, &soap_tmp_ns__add);
	soap->encodingStyle = "";
	if (!soap_get_ns__add(soap, &soap_tmp_ns__add, "ns:add", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__add(soap, soap_tmp_ns__add.a, soap_tmp_ns__add.b, &soap_tmp_double);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__addResponse(soap, &soap_tmp_ns__addResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__addResponse(soap, &soap_tmp_ns__addResponse, "ns:addResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__addResponse(soap, &soap_tmp_ns__addResponse, "ns:addResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getstep(struct soap *soap)
{	struct ns__getstep soap_tmp_ns__getstep;
	struct ns__getstepResponse soap_tmp_ns__getstepResponse;
	int soap_tmp_int;
	soap_default_ns__getstepResponse(soap, &soap_tmp_ns__getstepResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__getstepResponse.step = &soap_tmp_int;
	soap_default_ns__getstep(soap, &soap_tmp_ns__getstep);
	soap->encodingStyle = "";
	if (!soap_get_ns__getstep(soap, &soap_tmp_ns__getstep, "ns:getstep", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getstep(soap, soap_tmp_ns__getstep.id, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getstepResponse(soap, &soap_tmp_ns__getstepResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getstepResponse(soap, &soap_tmp_ns__getstepResponse, "ns:getstepResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getstepResponse(soap, &soap_tmp_ns__getstepResponse, "ns:getstepResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setstep(struct soap *soap)
{	struct ns__setstep soap_tmp_ns__setstep;
	struct ns__setstepResponse soap_tmp_ns__setstepResponse;
	int soap_tmp_int;
	soap_default_ns__setstepResponse(soap, &soap_tmp_ns__setstepResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setstepResponse.step = &soap_tmp_int;
	soap_default_ns__setstep(soap, &soap_tmp_ns__setstep);
	soap->encodingStyle = "";
	if (!soap_get_ns__setstep(soap, &soap_tmp_ns__setstep, "ns:setstep", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setstep(soap, soap_tmp_ns__setstep.id, soap_tmp_ns__setstep.newstep, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setstepResponse(soap, &soap_tmp_ns__setstepResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setstepResponse(soap, &soap_tmp_ns__setstepResponse, "ns:setstepResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setstepResponse(soap, &soap_tmp_ns__setstepResponse, "ns:setstepResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getnsteps(struct soap *soap)
{	struct ns__getnsteps soap_tmp_ns__getnsteps;
	struct ns__getnstepsResponse soap_tmp_ns__getnstepsResponse;
	int soap_tmp_int;
	soap_default_ns__getnstepsResponse(soap, &soap_tmp_ns__getnstepsResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__getnstepsResponse.nsstep = &soap_tmp_int;
	soap_default_ns__getnsteps(soap, &soap_tmp_ns__getnsteps);
	soap->encodingStyle = "";
	if (!soap_get_ns__getnsteps(soap, &soap_tmp_ns__getnsteps, "ns:getnsteps", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getnsteps(soap, soap_tmp_ns__getnsteps.id, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getnstepsResponse(soap, &soap_tmp_ns__getnstepsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getnstepsResponse(soap, &soap_tmp_ns__getnstepsResponse, "ns:getnstepsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getnstepsResponse(soap, &soap_tmp_ns__getnstepsResponse, "ns:getnstepsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setnsteps(struct soap *soap)
{	struct ns__setnsteps soap_tmp_ns__setnsteps;
	struct ns__setnstepsResponse soap_tmp_ns__setnstepsResponse;
	int soap_tmp_int;
	soap_default_ns__setnstepsResponse(soap, &soap_tmp_ns__setnstepsResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setnstepsResponse.nsteps = &soap_tmp_int;
	soap_default_ns__setnsteps(soap, &soap_tmp_ns__setnsteps);
	soap->encodingStyle = "";
	if (!soap_get_ns__setnsteps(soap, &soap_tmp_ns__setnsteps, "ns:setnsteps", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setnsteps(soap, soap_tmp_ns__setnsteps.id, soap_tmp_ns__setnsteps.newnsteps, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setnstepsResponse(soap, &soap_tmp_ns__setnstepsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setnstepsResponse(soap, &soap_tmp_ns__setnstepsResponse, "ns:setnstepsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setnstepsResponse(soap, &soap_tmp_ns__setnstepsResponse, "ns:setnstepsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__runsimulationstep(struct soap *soap)
{	struct ns__runsimulationstep soap_tmp_ns__runsimulationstep;
	struct ns__runsimulationstepResponse soap_tmp_ns__runsimulationstepResponse;
	int soap_tmp_int;
	soap_default_ns__runsimulationstepResponse(soap, &soap_tmp_ns__runsimulationstepResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__runsimulationstepResponse.status = &soap_tmp_int;
	soap_default_ns__runsimulationstep(soap, &soap_tmp_ns__runsimulationstep);
	soap->encodingStyle = "";
	if (!soap_get_ns__runsimulationstep(soap, &soap_tmp_ns__runsimulationstep, "ns:runsimulationstep", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__runsimulationstep(soap, soap_tmp_ns__runsimulationstep.id, soap_tmp_ns__runsimulationstep.istepnum, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__runsimulationstepResponse(soap, &soap_tmp_ns__runsimulationstepResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__runsimulationstepResponse(soap, &soap_tmp_ns__runsimulationstepResponse, "ns:runsimulationstepResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__runsimulationstepResponse(soap, &soap_tmp_ns__runsimulationstepResponse, "ns:runsimulationstepResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__runsimulation(struct soap *soap)
{	struct ns__runsimulation soap_tmp_ns__runsimulation;
	struct ns__runsimulationResponse soap_tmp_ns__runsimulationResponse;
	char * soap_tmp_string;
	soap_default_ns__runsimulationResponse(soap, &soap_tmp_ns__runsimulationResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__runsimulationResponse.result = &soap_tmp_string;
	soap_default_ns__runsimulation(soap, &soap_tmp_ns__runsimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__runsimulation(soap, &soap_tmp_ns__runsimulation, "ns:runsimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__runsimulation(soap, soap_tmp_ns__runsimulation.id, soap_tmp_ns__runsimulation.simfilecontent, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__runsimulationResponse(soap, &soap_tmp_ns__runsimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__runsimulationResponse(soap, &soap_tmp_ns__runsimulationResponse, "ns:runsimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__runsimulationResponse(soap, &soap_tmp_ns__runsimulationResponse, "ns:runsimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__requestsimulation(struct soap *soap)
{	struct ns__requestsimulation soap_tmp_ns__requestsimulation;
	struct ns__requestsimulationResponse soap_tmp_ns__requestsimulationResponse;
	int soap_tmp_int;
	soap_default_ns__requestsimulationResponse(soap, &soap_tmp_ns__requestsimulationResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__requestsimulationResponse.isimid = &soap_tmp_int;
	soap_default_ns__requestsimulation(soap, &soap_tmp_ns__requestsimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__requestsimulation(soap, &soap_tmp_ns__requestsimulation, "ns:requestsimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__requestsimulation(soap, soap_tmp_ns__requestsimulation.simfilecontent, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__requestsimulationResponse(soap, &soap_tmp_ns__requestsimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__requestsimulationResponse(soap, &soap_tmp_ns__requestsimulationResponse, "ns:requestsimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__requestsimulationResponse(soap, &soap_tmp_ns__requestsimulationResponse, "ns:requestsimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__runrequestedsimulation(struct soap *soap)
{	struct ns__runrequestedsimulation soap_tmp_ns__runrequestedsimulation;
	struct ns__runrequestedsimulationResponse soap_tmp_ns__runrequestedsimulationResponse;
	int soap_tmp_int;
	soap_default_ns__runrequestedsimulationResponse(soap, &soap_tmp_ns__runrequestedsimulationResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__runrequestedsimulationResponse.istatus = &soap_tmp_int;
	soap_default_ns__runrequestedsimulation(soap, &soap_tmp_ns__runrequestedsimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__runrequestedsimulation(soap, &soap_tmp_ns__runrequestedsimulation, "ns:runrequestedsimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__runrequestedsimulation(soap, soap_tmp_ns__runrequestedsimulation.isimid, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__runrequestedsimulationResponse(soap, &soap_tmp_ns__runrequestedsimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__runrequestedsimulationResponse(soap, &soap_tmp_ns__runrequestedsimulationResponse, "ns:runrequestedsimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__runrequestedsimulationResponse(soap, &soap_tmp_ns__runrequestedsimulationResponse, "ns:runrequestedsimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__submitsimulation(struct soap *soap)
{	struct ns__submitsimulation soap_tmp_ns__submitsimulation;
	struct ns__submitsimulationResponse soap_tmp_ns__submitsimulationResponse;
	int soap_tmp_int;
	soap_default_ns__submitsimulationResponse(soap, &soap_tmp_ns__submitsimulationResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__submitsimulationResponse.isimid = &soap_tmp_int;
	soap_default_ns__submitsimulation(soap, &soap_tmp_ns__submitsimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__submitsimulation(soap, &soap_tmp_ns__submitsimulation, "ns:submitsimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__submitsimulation(soap, soap_tmp_ns__submitsimulation.simfilecontent, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__submitsimulationResponse(soap, &soap_tmp_ns__submitsimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__submitsimulationResponse(soap, &soap_tmp_ns__submitsimulationResponse, "ns:submitsimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__submitsimulationResponse(soap, &soap_tmp_ns__submitsimulationResponse, "ns:submitsimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__simulationstatus(struct soap *soap)
{	struct ns__simulationstatus soap_tmp_ns__simulationstatus;
	struct ns__simulationstatusResponse soap_tmp_ns__simulationstatusResponse;
	int soap_tmp_int;
	soap_default_ns__simulationstatusResponse(soap, &soap_tmp_ns__simulationstatusResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__simulationstatusResponse.status = &soap_tmp_int;
	soap_default_ns__simulationstatus(soap, &soap_tmp_ns__simulationstatus);
	soap->encodingStyle = "";
	if (!soap_get_ns__simulationstatus(soap, &soap_tmp_ns__simulationstatus, "ns:simulationstatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__simulationstatus(soap, soap_tmp_ns__simulationstatus.isimid, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__simulationstatusResponse(soap, &soap_tmp_ns__simulationstatusResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__simulationstatusResponse(soap, &soap_tmp_ns__simulationstatusResponse, "ns:simulationstatusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__simulationstatusResponse(soap, &soap_tmp_ns__simulationstatusResponse, "ns:simulationstatusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setsimulationstatus(struct soap *soap)
{	struct ns__setsimulationstatus soap_tmp_ns__setsimulationstatus;
	struct ns__setsimulationstatusResponse soap_tmp_ns__setsimulationstatusResponse;
	int soap_tmp_int;
	soap_default_ns__setsimulationstatusResponse(soap, &soap_tmp_ns__setsimulationstatusResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setsimulationstatusResponse.status = &soap_tmp_int;
	soap_default_ns__setsimulationstatus(soap, &soap_tmp_ns__setsimulationstatus);
	soap->encodingStyle = "";
	if (!soap_get_ns__setsimulationstatus(soap, &soap_tmp_ns__setsimulationstatus, "ns:setsimulationstatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setsimulationstatus(soap, soap_tmp_ns__setsimulationstatus.newstatus, soap_tmp_ns__setsimulationstatus.isimid, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setsimulationstatusResponse(soap, &soap_tmp_ns__setsimulationstatusResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setsimulationstatusResponse(soap, &soap_tmp_ns__setsimulationstatusResponse, "ns:setsimulationstatusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setsimulationstatusResponse(soap, &soap_tmp_ns__setsimulationstatusResponse, "ns:setsimulationstatusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getsimulationresults(struct soap *soap)
{	struct ns__getsimulationresults soap_tmp_ns__getsimulationresults;
	struct ns__getsimulationresultsResponse soap_tmp_ns__getsimulationresultsResponse;
	char * soap_tmp_string;
	soap_default_ns__getsimulationresultsResponse(soap, &soap_tmp_ns__getsimulationresultsResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__getsimulationresultsResponse.result = &soap_tmp_string;
	soap_default_ns__getsimulationresults(soap, &soap_tmp_ns__getsimulationresults);
	soap->encodingStyle = "";
	if (!soap_get_ns__getsimulationresults(soap, &soap_tmp_ns__getsimulationresults, "ns:getsimulationresults", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getsimulationresults(soap, soap_tmp_ns__getsimulationresults.isimid, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getsimulationresultsResponse(soap, &soap_tmp_ns__getsimulationresultsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getsimulationresultsResponse(soap, &soap_tmp_ns__getsimulationresultsResponse, "ns:getsimulationresultsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getsimulationresultsResponse(soap, &soap_tmp_ns__getsimulationresultsResponse, "ns:getsimulationresultsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__deletesimulation(struct soap *soap)
{	struct ns__deletesimulation soap_tmp_ns__deletesimulation;
	struct ns__deletesimulationResponse soap_tmp_ns__deletesimulationResponse;
	int soap_tmp_int;
	soap_default_ns__deletesimulationResponse(soap, &soap_tmp_ns__deletesimulationResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__deletesimulationResponse.status = &soap_tmp_int;
	soap_default_ns__deletesimulation(soap, &soap_tmp_ns__deletesimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__deletesimulation(soap, &soap_tmp_ns__deletesimulation, "ns:deletesimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__deletesimulation(soap, soap_tmp_ns__deletesimulation.isimid, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__deletesimulationResponse(soap, &soap_tmp_ns__deletesimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__deletesimulationResponse(soap, &soap_tmp_ns__deletesimulationResponse, "ns:deletesimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__deletesimulationResponse(soap, &soap_tmp_ns__deletesimulationResponse, "ns:deletesimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__newsimulation(struct soap *soap)
{	struct ns__newsimulation soap_tmp_ns__newsimulation;
	struct ns__newsimulationResponse soap_tmp_ns__newsimulationResponse;
	int soap_tmp_int;
	soap_default_ns__newsimulationResponse(soap, &soap_tmp_ns__newsimulationResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__newsimulationResponse.status = &soap_tmp_int;
	soap_default_ns__newsimulation(soap, &soap_tmp_ns__newsimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__newsimulation(soap, &soap_tmp_ns__newsimulation, "ns:newsimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__newsimulation(soap, soap_tmp_ns__newsimulation.id, soap_tmp_ns__newsimulation.simname, soap_tmp_ns__newsimulation.xslname, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__newsimulationResponse(soap, &soap_tmp_ns__newsimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__newsimulationResponse(soap, &soap_tmp_ns__newsimulationResponse, "ns:newsimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__newsimulationResponse(soap, &soap_tmp_ns__newsimulationResponse, "ns:newsimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__createsimulation(struct soap *soap)
{	struct ns__createsimulation soap_tmp_ns__createsimulation;
	struct ns__createsimulationResponse soap_tmp_ns__createsimulationResponse;
	int soap_tmp_int;
	soap_default_ns__createsimulationResponse(soap, &soap_tmp_ns__createsimulationResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__createsimulationResponse.status = &soap_tmp_int;
	soap_default_ns__createsimulation(soap, &soap_tmp_ns__createsimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__createsimulation(soap, &soap_tmp_ns__createsimulation, "ns:createsimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__createsimulation(soap, soap_tmp_ns__createsimulation.id, soap_tmp_ns__createsimulation.filename, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__createsimulationResponse(soap, &soap_tmp_ns__createsimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__createsimulationResponse(soap, &soap_tmp_ns__createsimulationResponse, "ns:createsimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__createsimulationResponse(soap, &soap_tmp_ns__createsimulationResponse, "ns:createsimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__writelocalsimulation(struct soap *soap)
{	struct ns__writelocalsimulation soap_tmp_ns__writelocalsimulation;
	struct ns__writelocalsimulationResponse soap_tmp_ns__writelocalsimulationResponse;
	char * soap_tmp_string;
	soap_default_ns__writelocalsimulationResponse(soap, &soap_tmp_ns__writelocalsimulationResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__writelocalsimulationResponse.filecontent = &soap_tmp_string;
	soap_default_ns__writelocalsimulation(soap, &soap_tmp_ns__writelocalsimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__writelocalsimulation(soap, &soap_tmp_ns__writelocalsimulation, "ns:writelocalsimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__writelocalsimulation(soap, soap_tmp_ns__writelocalsimulation.id, soap_tmp_ns__writelocalsimulation.filename, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__writelocalsimulationResponse(soap, &soap_tmp_ns__writelocalsimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__writelocalsimulationResponse(soap, &soap_tmp_ns__writelocalsimulationResponse, "ns:writelocalsimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__writelocalsimulationResponse(soap, &soap_tmp_ns__writelocalsimulationResponse, "ns:writelocalsimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__readlocalsimulation(struct soap *soap)
{	struct ns__readlocalsimulation soap_tmp_ns__readlocalsimulation;
	struct ns__readlocalsimulationResponse soap_tmp_ns__readlocalsimulationResponse;
	int soap_tmp_int;
	soap_default_ns__readlocalsimulationResponse(soap, &soap_tmp_ns__readlocalsimulationResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__readlocalsimulationResponse.status = &soap_tmp_int;
	soap_default_ns__readlocalsimulation(soap, &soap_tmp_ns__readlocalsimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__readlocalsimulation(soap, &soap_tmp_ns__readlocalsimulation, "ns:readlocalsimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__readlocalsimulation(soap, soap_tmp_ns__readlocalsimulation.id, soap_tmp_ns__readlocalsimulation.filename, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__readlocalsimulationResponse(soap, &soap_tmp_ns__readlocalsimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__readlocalsimulationResponse(soap, &soap_tmp_ns__readlocalsimulationResponse, "ns:readlocalsimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__readlocalsimulationResponse(soap, &soap_tmp_ns__readlocalsimulationResponse, "ns:readlocalsimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__writesimulation(struct soap *soap)
{	struct ns__writesimulation soap_tmp_ns__writesimulation;
	struct ns__writesimulationResponse soap_tmp_ns__writesimulationResponse;
	char * soap_tmp_string;
	soap_default_ns__writesimulationResponse(soap, &soap_tmp_ns__writesimulationResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__writesimulationResponse.filecontent = &soap_tmp_string;
	soap_default_ns__writesimulation(soap, &soap_tmp_ns__writesimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__writesimulation(soap, &soap_tmp_ns__writesimulation, "ns:writesimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__writesimulation(soap, soap_tmp_ns__writesimulation.id, soap_tmp_ns__writesimulation.filename, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__writesimulationResponse(soap, &soap_tmp_ns__writesimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__writesimulationResponse(soap, &soap_tmp_ns__writesimulationResponse, "ns:writesimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__writesimulationResponse(soap, &soap_tmp_ns__writesimulationResponse, "ns:writesimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__readsimulation(struct soap *soap)
{	struct ns__readsimulation soap_tmp_ns__readsimulation;
	struct ns__readsimulationResponse soap_tmp_ns__readsimulationResponse;
	int soap_tmp_int;
	soap_default_ns__readsimulationResponse(soap, &soap_tmp_ns__readsimulationResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__readsimulationResponse.status = &soap_tmp_int;
	soap_default_ns__readsimulation(soap, &soap_tmp_ns__readsimulation);
	soap->encodingStyle = "";
	if (!soap_get_ns__readsimulation(soap, &soap_tmp_ns__readsimulation, "ns:readsimulation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__readsimulation(soap, soap_tmp_ns__readsimulation.id, soap_tmp_ns__readsimulation.filename, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__readsimulationResponse(soap, &soap_tmp_ns__readsimulationResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__readsimulationResponse(soap, &soap_tmp_ns__readsimulationResponse, "ns:readsimulationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__readsimulationResponse(soap, &soap_tmp_ns__readsimulationResponse, "ns:readsimulationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__exitiome(struct soap *soap)
{	struct ns__exitiome soap_tmp_ns__exitiome;
	struct ns__exitiomeResponse soap_tmp_ns__exitiomeResponse;
	int soap_tmp_int;
	soap_default_ns__exitiomeResponse(soap, &soap_tmp_ns__exitiomeResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__exitiomeResponse.status = &soap_tmp_int;
	soap_default_ns__exitiome(soap, &soap_tmp_ns__exitiome);
	soap->encodingStyle = "";
	if (!soap_get_ns__exitiome(soap, &soap_tmp_ns__exitiome, "ns:exitiome", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__exitiome(soap, soap_tmp_ns__exitiome.id, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__exitiomeResponse(soap, &soap_tmp_ns__exitiomeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__exitiomeResponse(soap, &soap_tmp_ns__exitiomeResponse, "ns:exitiomeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__exitiomeResponse(soap, &soap_tmp_ns__exitiomeResponse, "ns:exitiomeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparamdouble(struct soap *soap)
{	struct ns__addparamdouble soap_tmp_ns__addparamdouble;
	struct ns__addparamdoubleResponse soap_tmp_ns__addparamdoubleResponse;
	int soap_tmp_int;
	soap_default_ns__addparamdoubleResponse(soap, &soap_tmp_ns__addparamdoubleResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__addparamdoubleResponse.status = &soap_tmp_int;
	soap_default_ns__addparamdouble(soap, &soap_tmp_ns__addparamdouble);
	soap->encodingStyle = "";
	if (!soap_get_ns__addparamdouble(soap, &soap_tmp_ns__addparamdouble, "ns:addparamdouble", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__addparamdouble(soap, soap_tmp_ns__addparamdouble.id, soap_tmp_ns__addparamdouble.name, soap_tmp_ns__addparamdouble.value, soap_tmp_ns__addparamdouble.iflag, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__addparamdoubleResponse(soap, &soap_tmp_ns__addparamdoubleResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__addparamdoubleResponse(soap, &soap_tmp_ns__addparamdoubleResponse, "ns:addparamdoubleResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__addparamdoubleResponse(soap, &soap_tmp_ns__addparamdoubleResponse, "ns:addparamdoubleResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparamint(struct soap *soap)
{	struct ns__addparamint soap_tmp_ns__addparamint;
	struct ns__addparamintResponse soap_tmp_ns__addparamintResponse;
	int soap_tmp_int;
	soap_default_ns__addparamintResponse(soap, &soap_tmp_ns__addparamintResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__addparamintResponse.status = &soap_tmp_int;
	soap_default_ns__addparamint(soap, &soap_tmp_ns__addparamint);
	soap->encodingStyle = "";
	if (!soap_get_ns__addparamint(soap, &soap_tmp_ns__addparamint, "ns:addparamint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__addparamint(soap, soap_tmp_ns__addparamint.id, soap_tmp_ns__addparamint.name, soap_tmp_ns__addparamint.value, soap_tmp_ns__addparamint.iflag, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__addparamintResponse(soap, &soap_tmp_ns__addparamintResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__addparamintResponse(soap, &soap_tmp_ns__addparamintResponse, "ns:addparamintResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__addparamintResponse(soap, &soap_tmp_ns__addparamintResponse, "ns:addparamintResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparamvec(struct soap *soap)
{	struct ns__addparamvec soap_tmp_ns__addparamvec;
	struct ns__addparamvecResponse soap_tmp_ns__addparamvecResponse;
	int soap_tmp_int;
	soap_default_ns__addparamvecResponse(soap, &soap_tmp_ns__addparamvecResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__addparamvecResponse.status = &soap_tmp_int;
	soap_default_ns__addparamvec(soap, &soap_tmp_ns__addparamvec);
	soap->encodingStyle = "";
	if (!soap_get_ns__addparamvec(soap, &soap_tmp_ns__addparamvec, "ns:addparamvec", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__addparamvec(soap, soap_tmp_ns__addparamvec.id, soap_tmp_ns__addparamvec.name, soap_tmp_ns__addparamvec.value, soap_tmp_ns__addparamvec.n, soap_tmp_ns__addparamvec.iflag, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__addparamvecResponse(soap, &soap_tmp_ns__addparamvecResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__addparamvecResponse(soap, &soap_tmp_ns__addparamvecResponse, "ns:addparamvecResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__addparamvecResponse(soap, &soap_tmp_ns__addparamvecResponse, "ns:addparamvecResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparammat(struct soap *soap)
{	struct ns__addparammat soap_tmp_ns__addparammat;
	struct ns__addparammatResponse soap_tmp_ns__addparammatResponse;
	int soap_tmp_int;
	soap_default_ns__addparammatResponse(soap, &soap_tmp_ns__addparammatResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__addparammatResponse.status = &soap_tmp_int;
	soap_default_ns__addparammat(soap, &soap_tmp_ns__addparammat);
	soap->encodingStyle = "";
	if (!soap_get_ns__addparammat(soap, &soap_tmp_ns__addparammat, "ns:addparammat", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__addparammat(soap, soap_tmp_ns__addparammat.id, soap_tmp_ns__addparammat.name, soap_tmp_ns__addparammat.value, soap_tmp_ns__addparammat.nr, soap_tmp_ns__addparammat.nc, soap_tmp_ns__addparammat.iflag, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__addparammatResponse(soap, &soap_tmp_ns__addparammatResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__addparammatResponse(soap, &soap_tmp_ns__addparammatResponse, "ns:addparammatResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__addparammatResponse(soap, &soap_tmp_ns__addparammatResponse, "ns:addparammatResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparamstring(struct soap *soap)
{	struct ns__addparamstring soap_tmp_ns__addparamstring;
	struct ns__addparamstringResponse soap_tmp_ns__addparamstringResponse;
	int soap_tmp_int;
	soap_default_ns__addparamstringResponse(soap, &soap_tmp_ns__addparamstringResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__addparamstringResponse.status = &soap_tmp_int;
	soap_default_ns__addparamstring(soap, &soap_tmp_ns__addparamstring);
	soap->encodingStyle = "";
	if (!soap_get_ns__addparamstring(soap, &soap_tmp_ns__addparamstring, "ns:addparamstring", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__addparamstring(soap, soap_tmp_ns__addparamstring.id, soap_tmp_ns__addparamstring.name, soap_tmp_ns__addparamstring.value, soap_tmp_ns__addparamstring.iflag, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__addparamstringResponse(soap, &soap_tmp_ns__addparamstringResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__addparamstringResponse(soap, &soap_tmp_ns__addparamstringResponse, "ns:addparamstringResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__addparamstringResponse(soap, &soap_tmp_ns__addparamstringResponse, "ns:addparamstringResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparammmat3d(struct soap *soap)
{	struct ns__addparammmat3d soap_tmp_ns__addparammmat3d;
	struct ns__addparammmat3dResponse soap_tmp_ns__addparammmat3dResponse;
	int soap_tmp_int;
	soap_default_ns__addparammmat3dResponse(soap, &soap_tmp_ns__addparammmat3dResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__addparammmat3dResponse.status = &soap_tmp_int;
	soap_default_ns__addparammmat3d(soap, &soap_tmp_ns__addparammmat3d);
	soap->encodingStyle = "";
	if (!soap_get_ns__addparammmat3d(soap, &soap_tmp_ns__addparammmat3d, "ns:addparammmat3d", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__addparammmat3d(soap, soap_tmp_ns__addparammmat3d.id, soap_tmp_ns__addparammmat3d.name, soap_tmp_ns__addparammmat3d.value, soap_tmp_ns__addparammmat3d.n, soap_tmp_ns__addparammmat3d.p, soap_tmp_ns__addparammmat3d.q, soap_tmp_ns__addparammmat3d.nr, soap_tmp_ns__addparammmat3d.nc, soap_tmp_ns__addparammmat3d.iflag, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__addparammmat3dResponse(soap, &soap_tmp_ns__addparammmat3dResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__addparammmat3dResponse(soap, &soap_tmp_ns__addparammmat3dResponse, "ns:addparammmat3dResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__addparammmat3dResponse(soap, &soap_tmp_ns__addparammmat3dResponse, "ns:addparammmat3dResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addmetadata(struct soap *soap)
{	struct ns__addmetadata soap_tmp_ns__addmetadata;
	struct ns__addmetadataResponse soap_tmp_ns__addmetadataResponse;
	int soap_tmp_int;
	soap_default_ns__addmetadataResponse(soap, &soap_tmp_ns__addmetadataResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__addmetadataResponse.status = &soap_tmp_int;
	soap_default_ns__addmetadata(soap, &soap_tmp_ns__addmetadata);
	soap->encodingStyle = "";
	if (!soap_get_ns__addmetadata(soap, &soap_tmp_ns__addmetadata, "ns:addmetadata", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__addmetadata(soap, soap_tmp_ns__addmetadata.id, soap_tmp_ns__addmetadata.name, soap_tmp_ns__addmetadata.property, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__addmetadataResponse(soap, &soap_tmp_ns__addmetadataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__addmetadataResponse(soap, &soap_tmp_ns__addmetadataResponse, "ns:addmetadataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__addmetadataResponse(soap, &soap_tmp_ns__addmetadataResponse, "ns:addmetadataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparamdouble(struct soap *soap)
{	struct ns__getparamdouble soap_tmp_ns__getparamdouble;
	struct ns__getparamdoubleResponse soap_tmp_ns__getparamdoubleResponse;
	double soap_tmp_double;
	soap_default_ns__getparamdoubleResponse(soap, &soap_tmp_ns__getparamdoubleResponse);
	soap_default_double(soap, &soap_tmp_double);
	soap_tmp_ns__getparamdoubleResponse.value = &soap_tmp_double;
	soap_default_ns__getparamdouble(soap, &soap_tmp_ns__getparamdouble);
	soap->encodingStyle = "";
	if (!soap_get_ns__getparamdouble(soap, &soap_tmp_ns__getparamdouble, "ns:getparamdouble", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getparamdouble(soap, soap_tmp_ns__getparamdouble.id, soap_tmp_ns__getparamdouble.name, &soap_tmp_double);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getparamdoubleResponse(soap, &soap_tmp_ns__getparamdoubleResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getparamdoubleResponse(soap, &soap_tmp_ns__getparamdoubleResponse, "ns:getparamdoubleResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getparamdoubleResponse(soap, &soap_tmp_ns__getparamdoubleResponse, "ns:getparamdoubleResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparamint(struct soap *soap)
{	struct ns__getparamint soap_tmp_ns__getparamint;
	struct ns__getparamintResponse soap_tmp_ns__getparamintResponse;
	int soap_tmp_int;
	soap_default_ns__getparamintResponse(soap, &soap_tmp_ns__getparamintResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__getparamintResponse.value = &soap_tmp_int;
	soap_default_ns__getparamint(soap, &soap_tmp_ns__getparamint);
	soap->encodingStyle = "";
	if (!soap_get_ns__getparamint(soap, &soap_tmp_ns__getparamint, "ns:getparamint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getparamint(soap, soap_tmp_ns__getparamint.id, soap_tmp_ns__getparamint.name, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getparamintResponse(soap, &soap_tmp_ns__getparamintResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getparamintResponse(soap, &soap_tmp_ns__getparamintResponse, "ns:getparamintResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getparamintResponse(soap, &soap_tmp_ns__getparamintResponse, "ns:getparamintResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparamvec(struct soap *soap)
{	struct ns__getparamvec soap_tmp_ns__getparamvec;
	struct ns__getparamvecResponse soap_tmp_ns__getparamvecResponse;
	struct fdata * soap_tmp_PointerTofdata;
	soap_default_ns__getparamvecResponse(soap, &soap_tmp_ns__getparamvecResponse);
	soap_tmp_PointerTofdata = NULL;
	soap_tmp_ns__getparamvecResponse.dval = &soap_tmp_PointerTofdata;
	soap_default_ns__getparamvec(soap, &soap_tmp_ns__getparamvec);
	soap->encodingStyle = "";
	if (!soap_get_ns__getparamvec(soap, &soap_tmp_ns__getparamvec, "ns:getparamvec", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getparamvec(soap, soap_tmp_ns__getparamvec.id, soap_tmp_ns__getparamvec.name, soap_tmp_ns__getparamvec.n, &soap_tmp_PointerTofdata);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getparamvecResponse(soap, &soap_tmp_ns__getparamvecResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getparamvecResponse(soap, &soap_tmp_ns__getparamvecResponse, "ns:getparamvecResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getparamvecResponse(soap, &soap_tmp_ns__getparamvecResponse, "ns:getparamvecResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparammat(struct soap *soap)
{	struct ns__getparammat soap_tmp_ns__getparammat;
	struct ns__getparammatResponse soap_tmp_ns__getparammatResponse;
	struct fdata * soap_tmp_PointerTofdata;
	soap_default_ns__getparammatResponse(soap, &soap_tmp_ns__getparammatResponse);
	soap_tmp_PointerTofdata = NULL;
	soap_tmp_ns__getparammatResponse.dval = &soap_tmp_PointerTofdata;
	soap_default_ns__getparammat(soap, &soap_tmp_ns__getparammat);
	soap->encodingStyle = "";
	if (!soap_get_ns__getparammat(soap, &soap_tmp_ns__getparammat, "ns:getparammat", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getparammat(soap, soap_tmp_ns__getparammat.id, soap_tmp_ns__getparammat.name, soap_tmp_ns__getparammat.nr, soap_tmp_ns__getparammat.nc, &soap_tmp_PointerTofdata);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getparammatResponse(soap, &soap_tmp_ns__getparammatResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getparammatResponse(soap, &soap_tmp_ns__getparammatResponse, "ns:getparammatResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getparammatResponse(soap, &soap_tmp_ns__getparammatResponse, "ns:getparammatResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparamstring(struct soap *soap)
{	struct ns__getparamstring soap_tmp_ns__getparamstring;
	struct ns__getparamstringResponse soap_tmp_ns__getparamstringResponse;
	char * soap_tmp_string;
	soap_default_ns__getparamstringResponse(soap, &soap_tmp_ns__getparamstringResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__getparamstringResponse.value = &soap_tmp_string;
	soap_default_ns__getparamstring(soap, &soap_tmp_ns__getparamstring);
	soap->encodingStyle = "";
	if (!soap_get_ns__getparamstring(soap, &soap_tmp_ns__getparamstring, "ns:getparamstring", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getparamstring(soap, soap_tmp_ns__getparamstring.id, soap_tmp_ns__getparamstring.name, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getparamstringResponse(soap, &soap_tmp_ns__getparamstringResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getparamstringResponse(soap, &soap_tmp_ns__getparamstringResponse, "ns:getparamstringResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getparamstringResponse(soap, &soap_tmp_ns__getparamstringResponse, "ns:getparamstringResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparammmat3d(struct soap *soap)
{	struct ns__getparammmat3d soap_tmp_ns__getparammmat3d;
	struct ns__getparammmat3dResponse soap_tmp_ns__getparammmat3dResponse;
	struct fdata * soap_tmp_PointerTofdata;
	soap_default_ns__getparammmat3dResponse(soap, &soap_tmp_ns__getparammmat3dResponse);
	soap_tmp_PointerTofdata = NULL;
	soap_tmp_ns__getparammmat3dResponse.mmat3d = &soap_tmp_PointerTofdata;
	soap_default_ns__getparammmat3d(soap, &soap_tmp_ns__getparammmat3d);
	soap->encodingStyle = "";
	if (!soap_get_ns__getparammmat3d(soap, &soap_tmp_ns__getparammmat3d, "ns:getparammmat3d", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getparammmat3d(soap, soap_tmp_ns__getparammmat3d.id, soap_tmp_ns__getparammmat3d.name, soap_tmp_ns__getparammmat3d.n, soap_tmp_ns__getparammmat3d.p, soap_tmp_ns__getparammmat3d.q, soap_tmp_ns__getparammmat3d.nr, soap_tmp_ns__getparammmat3d.nc, &soap_tmp_PointerTofdata);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getparammmat3dResponse(soap, &soap_tmp_ns__getparammmat3dResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getparammmat3dResponse(soap, &soap_tmp_ns__getparammmat3dResponse, "ns:getparammmat3dResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getparammmat3dResponse(soap, &soap_tmp_ns__getparammmat3dResponse, "ns:getparammmat3dResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getmetadata(struct soap *soap)
{	struct ns__getmetadata soap_tmp_ns__getmetadata;
	struct ns__getmetadataResponse soap_tmp_ns__getmetadataResponse;
	char * soap_tmp_string;
	soap_default_ns__getmetadataResponse(soap, &soap_tmp_ns__getmetadataResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__getmetadataResponse.property = &soap_tmp_string;
	soap_default_ns__getmetadata(soap, &soap_tmp_ns__getmetadata);
	soap->encodingStyle = "";
	if (!soap_get_ns__getmetadata(soap, &soap_tmp_ns__getmetadata, "ns:getmetadata", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getmetadata(soap, soap_tmp_ns__getmetadata.id, soap_tmp_ns__getmetadata.name, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getmetadataResponse(soap, &soap_tmp_ns__getmetadataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getmetadataResponse(soap, &soap_tmp_ns__getmetadataResponse, "ns:getmetadataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getmetadataResponse(soap, &soap_tmp_ns__getmetadataResponse, "ns:getmetadataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparamdouble(struct soap *soap)
{	struct ns__setparamdouble soap_tmp_ns__setparamdouble;
	struct ns__setparamdoubleResponse soap_tmp_ns__setparamdoubleResponse;
	int soap_tmp_int;
	soap_default_ns__setparamdoubleResponse(soap, &soap_tmp_ns__setparamdoubleResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setparamdoubleResponse.status = &soap_tmp_int;
	soap_default_ns__setparamdouble(soap, &soap_tmp_ns__setparamdouble);
	soap->encodingStyle = "";
	if (!soap_get_ns__setparamdouble(soap, &soap_tmp_ns__setparamdouble, "ns:setparamdouble", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setparamdouble(soap, soap_tmp_ns__setparamdouble.id, soap_tmp_ns__setparamdouble.name, soap_tmp_ns__setparamdouble.value, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setparamdoubleResponse(soap, &soap_tmp_ns__setparamdoubleResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setparamdoubleResponse(soap, &soap_tmp_ns__setparamdoubleResponse, "ns:setparamdoubleResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setparamdoubleResponse(soap, &soap_tmp_ns__setparamdoubleResponse, "ns:setparamdoubleResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparamint(struct soap *soap)
{	struct ns__setparamint soap_tmp_ns__setparamint;
	struct ns__setparamintResponse soap_tmp_ns__setparamintResponse;
	int soap_tmp_int;
	soap_default_ns__setparamintResponse(soap, &soap_tmp_ns__setparamintResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setparamintResponse.status = &soap_tmp_int;
	soap_default_ns__setparamint(soap, &soap_tmp_ns__setparamint);
	soap->encodingStyle = "";
	if (!soap_get_ns__setparamint(soap, &soap_tmp_ns__setparamint, "ns:setparamint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setparamint(soap, soap_tmp_ns__setparamint.id, soap_tmp_ns__setparamint.name, soap_tmp_ns__setparamint.value, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setparamintResponse(soap, &soap_tmp_ns__setparamintResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setparamintResponse(soap, &soap_tmp_ns__setparamintResponse, "ns:setparamintResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setparamintResponse(soap, &soap_tmp_ns__setparamintResponse, "ns:setparamintResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparamvec(struct soap *soap)
{	struct ns__setparamvec soap_tmp_ns__setparamvec;
	struct ns__setparamvecResponse soap_tmp_ns__setparamvecResponse;
	int soap_tmp_int;
	soap_default_ns__setparamvecResponse(soap, &soap_tmp_ns__setparamvecResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setparamvecResponse.status = &soap_tmp_int;
	soap_default_ns__setparamvec(soap, &soap_tmp_ns__setparamvec);
	soap->encodingStyle = "";
	if (!soap_get_ns__setparamvec(soap, &soap_tmp_ns__setparamvec, "ns:setparamvec", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setparamvec(soap, soap_tmp_ns__setparamvec.id, soap_tmp_ns__setparamvec.name, soap_tmp_ns__setparamvec.value, soap_tmp_ns__setparamvec.n, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setparamvecResponse(soap, &soap_tmp_ns__setparamvecResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setparamvecResponse(soap, &soap_tmp_ns__setparamvecResponse, "ns:setparamvecResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setparamvecResponse(soap, &soap_tmp_ns__setparamvecResponse, "ns:setparamvecResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparammat(struct soap *soap)
{	struct ns__setparammat soap_tmp_ns__setparammat;
	struct ns__setparammatResponse soap_tmp_ns__setparammatResponse;
	int soap_tmp_int;
	soap_default_ns__setparammatResponse(soap, &soap_tmp_ns__setparammatResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setparammatResponse.status = &soap_tmp_int;
	soap_default_ns__setparammat(soap, &soap_tmp_ns__setparammat);
	soap->encodingStyle = "";
	if (!soap_get_ns__setparammat(soap, &soap_tmp_ns__setparammat, "ns:setparammat", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setparammat(soap, soap_tmp_ns__setparammat.id, soap_tmp_ns__setparammat.name, soap_tmp_ns__setparammat.value, soap_tmp_ns__setparammat.nr, soap_tmp_ns__setparammat.nc, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setparammatResponse(soap, &soap_tmp_ns__setparammatResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setparammatResponse(soap, &soap_tmp_ns__setparammatResponse, "ns:setparammatResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setparammatResponse(soap, &soap_tmp_ns__setparammatResponse, "ns:setparammatResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparamstring(struct soap *soap)
{	struct ns__setparamstring soap_tmp_ns__setparamstring;
	struct ns__setparamstringResponse soap_tmp_ns__setparamstringResponse;
	int soap_tmp_int;
	soap_default_ns__setparamstringResponse(soap, &soap_tmp_ns__setparamstringResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setparamstringResponse.status = &soap_tmp_int;
	soap_default_ns__setparamstring(soap, &soap_tmp_ns__setparamstring);
	soap->encodingStyle = "";
	if (!soap_get_ns__setparamstring(soap, &soap_tmp_ns__setparamstring, "ns:setparamstring", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setparamstring(soap, soap_tmp_ns__setparamstring.id, soap_tmp_ns__setparamstring.name, soap_tmp_ns__setparamstring.value, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setparamstringResponse(soap, &soap_tmp_ns__setparamstringResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setparamstringResponse(soap, &soap_tmp_ns__setparamstringResponse, "ns:setparamstringResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setparamstringResponse(soap, &soap_tmp_ns__setparamstringResponse, "ns:setparamstringResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparammmat3d(struct soap *soap)
{	struct ns__setparammmat3d soap_tmp_ns__setparammmat3d;
	struct ns__setparammmat3dResponse soap_tmp_ns__setparammmat3dResponse;
	int soap_tmp_int;
	soap_default_ns__setparammmat3dResponse(soap, &soap_tmp_ns__setparammmat3dResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setparammmat3dResponse.status = &soap_tmp_int;
	soap_default_ns__setparammmat3d(soap, &soap_tmp_ns__setparammmat3d);
	soap->encodingStyle = "";
	if (!soap_get_ns__setparammmat3d(soap, &soap_tmp_ns__setparammmat3d, "ns:setparammmat3d", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setparammmat3d(soap, soap_tmp_ns__setparammmat3d.id, soap_tmp_ns__setparammmat3d.name, soap_tmp_ns__setparammmat3d.value, soap_tmp_ns__setparammmat3d.n, soap_tmp_ns__setparammmat3d.p, soap_tmp_ns__setparammmat3d.q, soap_tmp_ns__setparammmat3d.nr, soap_tmp_ns__setparammmat3d.nc, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setparammmat3dResponse(soap, &soap_tmp_ns__setparammmat3dResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setparammmat3dResponse(soap, &soap_tmp_ns__setparammmat3dResponse, "ns:setparammmat3dResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setparammmat3dResponse(soap, &soap_tmp_ns__setparammmat3dResponse, "ns:setparammmat3dResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setmetadata(struct soap *soap)
{	struct ns__setmetadata soap_tmp_ns__setmetadata;
	struct ns__setmetadataResponse soap_tmp_ns__setmetadataResponse;
	int soap_tmp_int;
	soap_default_ns__setmetadataResponse(soap, &soap_tmp_ns__setmetadataResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setmetadataResponse.status = &soap_tmp_int;
	soap_default_ns__setmetadata(soap, &soap_tmp_ns__setmetadata);
	soap->encodingStyle = "";
	if (!soap_get_ns__setmetadata(soap, &soap_tmp_ns__setmetadata, "ns:setmetadata", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setmetadata(soap, soap_tmp_ns__setmetadata.id, soap_tmp_ns__setmetadata.name, soap_tmp_ns__setmetadata.property, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setmetadataResponse(soap, &soap_tmp_ns__setmetadataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setmetadataResponse(soap, &soap_tmp_ns__setmetadataResponse, "ns:setmetadataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setmetadataResponse(soap, &soap_tmp_ns__setmetadataResponse, "ns:setmetadataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__listmetadata(struct soap *soap)
{	struct ns__listmetadata soap_tmp_ns__listmetadata;
	struct ns__listmetadataResponse soap_tmp_ns__listmetadataResponse;
	char * soap_tmp_string;
	soap_default_ns__listmetadataResponse(soap, &soap_tmp_ns__listmetadataResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__listmetadataResponse.list = &soap_tmp_string;
	soap_default_ns__listmetadata(soap, &soap_tmp_ns__listmetadata);
	soap->encodingStyle = "";
	if (!soap_get_ns__listmetadata(soap, &soap_tmp_ns__listmetadata, "ns:listmetadata", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__listmetadata(soap, soap_tmp_ns__listmetadata.id, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__listmetadataResponse(soap, &soap_tmp_ns__listmetadataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__listmetadataResponse(soap, &soap_tmp_ns__listmetadataResponse, "ns:listmetadataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__listmetadataResponse(soap, &soap_tmp_ns__listmetadataResponse, "ns:listmetadataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__deletemetadata(struct soap *soap)
{	struct ns__deletemetadata soap_tmp_ns__deletemetadata;
	struct ns__deletemetadataResponse soap_tmp_ns__deletemetadataResponse;
	int soap_tmp_int;
	soap_default_ns__deletemetadataResponse(soap, &soap_tmp_ns__deletemetadataResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__deletemetadataResponse.status = &soap_tmp_int;
	soap_default_ns__deletemetadata(soap, &soap_tmp_ns__deletemetadata);
	soap->encodingStyle = "";
	if (!soap_get_ns__deletemetadata(soap, &soap_tmp_ns__deletemetadata, "ns:deletemetadata", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__deletemetadata(soap, soap_tmp_ns__deletemetadata.id, soap_tmp_ns__deletemetadata.name, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__deletemetadataResponse(soap, &soap_tmp_ns__deletemetadataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__deletemetadataResponse(soap, &soap_tmp_ns__deletemetadataResponse, "ns:deletemetadataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__deletemetadataResponse(soap, &soap_tmp_ns__deletemetadataResponse, "ns:deletemetadataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__deleteparam(struct soap *soap)
{	struct ns__deleteparam soap_tmp_ns__deleteparam;
	struct ns__deleteparamResponse soap_tmp_ns__deleteparamResponse;
	int soap_tmp_int;
	soap_default_ns__deleteparamResponse(soap, &soap_tmp_ns__deleteparamResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__deleteparamResponse.status = &soap_tmp_int;
	soap_default_ns__deleteparam(soap, &soap_tmp_ns__deleteparam);
	soap->encodingStyle = "";
	if (!soap_get_ns__deleteparam(soap, &soap_tmp_ns__deleteparam, "ns:deleteparam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__deleteparam(soap, soap_tmp_ns__deleteparam.name, soap_tmp_ns__deleteparam.id, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__deleteparamResponse(soap, &soap_tmp_ns__deleteparamResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__deleteparamResponse(soap, &soap_tmp_ns__deleteparamResponse, "ns:deleteparamResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__deleteparamResponse(soap, &soap_tmp_ns__deleteparamResponse, "ns:deleteparamResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__listparam(struct soap *soap)
{	struct ns__listparam soap_tmp_ns__listparam;
	struct ns__listparamResponse soap_tmp_ns__listparamResponse;
	char * soap_tmp_string;
	soap_default_ns__listparamResponse(soap, &soap_tmp_ns__listparamResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__listparamResponse.list = &soap_tmp_string;
	soap_default_ns__listparam(soap, &soap_tmp_ns__listparam);
	soap->encodingStyle = "";
	if (!soap_get_ns__listparam(soap, &soap_tmp_ns__listparam, "ns:listparam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__listparam(soap, soap_tmp_ns__listparam.type, soap_tmp_ns__listparam.id, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__listparamResponse(soap, &soap_tmp_ns__listparamResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__listparamResponse(soap, &soap_tmp_ns__listparamResponse, "ns:listparamResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__listparamResponse(soap, &soap_tmp_ns__listparamResponse, "ns:listparamResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getnumobj(struct soap *soap)
{	struct ns__getnumobj soap_tmp_ns__getnumobj;
	struct ns__getnumobjResponse soap_tmp_ns__getnumobjResponse;
	int soap_tmp_int;
	soap_default_ns__getnumobjResponse(soap, &soap_tmp_ns__getnumobjResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__getnumobjResponse.numobj = &soap_tmp_int;
	soap_default_ns__getnumobj(soap, &soap_tmp_ns__getnumobj);
	soap->encodingStyle = "";
	if (!soap_get_ns__getnumobj(soap, &soap_tmp_ns__getnumobj, "ns:getnumobj", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getnumobj(soap, soap_tmp_ns__getnumobj.id, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getnumobjResponse(soap, &soap_tmp_ns__getnumobjResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getnumobjResponse(soap, &soap_tmp_ns__getnumobjResponse, "ns:getnumobjResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getnumobjResponse(soap, &soap_tmp_ns__getnumobjResponse, "ns:getnumobjResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getobjnum(struct soap *soap)
{	struct ns__getobjnum soap_tmp_ns__getobjnum;
	struct ns__getobjnumResponse soap_tmp_ns__getobjnumResponse;
	int soap_tmp_int;
	soap_default_ns__getobjnumResponse(soap, &soap_tmp_ns__getobjnumResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__getobjnumResponse.objnum = &soap_tmp_int;
	soap_default_ns__getobjnum(soap, &soap_tmp_ns__getobjnum);
	soap->encodingStyle = "";
	if (!soap_get_ns__getobjnum(soap, &soap_tmp_ns__getobjnum, "ns:getobjnum", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getobjnum(soap, soap_tmp_ns__getobjnum.id, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__getobjnumResponse(soap, &soap_tmp_ns__getobjnumResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getobjnumResponse(soap, &soap_tmp_ns__getobjnumResponse, "ns:getobjnumResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getobjnumResponse(soap, &soap_tmp_ns__getobjnumResponse, "ns:getobjnumResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__testgroupbarrier(struct soap *soap)
{	struct ns__testgroupbarrier soap_tmp_ns__testgroupbarrier;
	struct ns__testgroupbarrierResponse soap_tmp_ns__testgroupbarrierResponse;
	int soap_tmp_int;
	soap_default_ns__testgroupbarrierResponse(soap, &soap_tmp_ns__testgroupbarrierResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__testgroupbarrierResponse.state = &soap_tmp_int;
	soap_default_ns__testgroupbarrier(soap, &soap_tmp_ns__testgroupbarrier);
	soap->encodingStyle = "";
	if (!soap_get_ns__testgroupbarrier(soap, &soap_tmp_ns__testgroupbarrier, "ns:testgroupbarrier", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__testgroupbarrier(soap, soap_tmp_ns__testgroupbarrier.id, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__testgroupbarrierResponse(soap, &soap_tmp_ns__testgroupbarrierResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__testgroupbarrierResponse(soap, &soap_tmp_ns__testgroupbarrierResponse, "ns:testgroupbarrierResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__testgroupbarrierResponse(soap, &soap_tmp_ns__testgroupbarrierResponse, "ns:testgroupbarrierResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setgroupbarrier(struct soap *soap)
{	struct ns__setgroupbarrier soap_tmp_ns__setgroupbarrier;
	struct ns__setgroupbarrierResponse soap_tmp_ns__setgroupbarrierResponse;
	int soap_tmp_int;
	soap_default_ns__setgroupbarrierResponse(soap, &soap_tmp_ns__setgroupbarrierResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__setgroupbarrierResponse.newstate = &soap_tmp_int;
	soap_default_ns__setgroupbarrier(soap, &soap_tmp_ns__setgroupbarrier);
	soap->encodingStyle = "";
	if (!soap_get_ns__setgroupbarrier(soap, &soap_tmp_ns__setgroupbarrier, "ns:setgroupbarrier", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__setgroupbarrier(soap, soap_tmp_ns__setgroupbarrier.id, soap_tmp_ns__setgroupbarrier.state, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__setgroupbarrierResponse(soap, &soap_tmp_ns__setgroupbarrierResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__setgroupbarrierResponse(soap, &soap_tmp_ns__setgroupbarrierResponse, "ns:setgroupbarrierResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__setgroupbarrierResponse(soap, &soap_tmp_ns__setgroupbarrierResponse, "ns:setgroupbarrierResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

/* End of soapServer.cpp */
