function result = runsimulation(obj,id,simfilecontent)
%runsimulation(obj,id,simfilecontent)
%
%   Service definition of function ns__runsimulation
%   
%     Input:
%       id = (int)
%       simfilecontent = (string)
%   
%     Output:
%       result = (string)

% Build up the argument lists.
values = { ...
   id, ...
   simfilecontent, ...
   };
names = { ...
   'id', ...
   'simfilecontent', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'runsimulation', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
result = parseSoapResponse(response);
