function status = setparammat(obj,id,name,value,nr,nc)
%setparammat(obj,id,name,value,nr,nc)
%
%   Service definition of function ns__setparammat
%   
%     Input:
%       id = (int)
%       name = (string)
%       value = (Array)
%       nr = (int)
%       nc = (int)
%   
%     Output:
%       status = (int)

% Build up the argument lists.
values = { ...
   id, ...
   name, ...
   value, ...
   nr, ...
   nc, ...
   };
names = { ...
   'id', ...
   'name', ...
   'value', ...
   'nr', ...
   'nc', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   'Array', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'setparammat', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
status = parseSoapResponse(response);
