function status = addparammmat3d(obj,id,name,value,n,p,q,nr,nc,iflag)
%addparammmat3d(obj,id,name,value,n,p,q,nr,nc,iflag)
%
%   Service definition of function ns__addparammmat3d
%   
%     Input:
%       id = (int)
%       name = (string)
%       value = (Array)
%       n = (int)
%       p = (int)
%       q = (int)
%       nr = (int)
%       nc = (int)
%       iflag = (int)
%   
%     Output:
%       status = (int)

% Build up the argument lists.
values = { ...
   id, ...
   name, ...
   value, ...
   n, ...
   p, ...
   q, ...
   nr, ...
   nc, ...
   iflag, ...
   };
names = { ...
   'id', ...
   'name', ...
   'value', ...
   'n', ...
   'p', ...
   'q', ...
   'nr', ...
   'nc', ...
   'iflag', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   'Array', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'addparammmat3d', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
status = parseSoapResponse(response);
