function objnum = getobjnum(obj,id)
%getobjnum(obj,id)
%
%   Service definition of function ns__getobjnum
%   
%     Input:
%       id = (int)
%   
%     Output:
%       objnum = (int)

% Build up the argument lists.
values = { ...
   id, ...
   };
names = { ...
   'id', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'getobjnum', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
objnum = parseSoapResponse(response);
