function dval = getparamvec(obj,id,name,n)
%getparamvec(obj,id,name,n)
%
%   Service definition of function ns__getparamvec
%   
%     Input:
%       id = (int)
%       name = (string)
%       n = (int)
%   
%     Output:
%       dval = (Array)

% Build up the argument lists.
values = { ...
   id, ...
   name, ...
   n, ...
   };
names = { ...
   'id', ...
   'name', ...
   'n', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'getparamvec', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
dval = parseSoapResponse(response);
