function mmat3d = getparammmat3d(obj,id,name,n,p,q,nr,nc)
%getparammmat3d(obj,id,name,n,p,q,nr,nc)
%
%   Service definition of function ns__getparammmat3d
%   
%     Input:
%       id = (int)
%       name = (string)
%       n = (int)
%       p = (int)
%       q = (int)
%       nr = (int)
%       nc = (int)
%   
%     Output:
%       mmat3d = (Array)

% Build up the argument lists.
values = { ...
   id, ...
   name, ...
   n, ...
   p, ...
   q, ...
   nr, ...
   nc, ...
   };
names = { ...
   'id', ...
   'name', ...
   'n', ...
   'p', ...
   'q', ...
   'nr', ...
   'nc', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'getparammmat3d', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
mmat3d = parseSoapResponse(response);
