function status = newsimulation(obj,id,simname,xslname)
%newsimulation(obj,id,simname,xslname)
%
%   Service definition of function ns__newsimulation
%   
%     Input:
%       id = (int)
%       simname = (string)
%       xslname = (string)
%   
%     Output:
%       status = (int)

% Build up the argument lists.
values = { ...
   id, ...
   simname, ...
   xslname, ...
   };
names = { ...
   'id', ...
   'simname', ...
   'xslname', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'newsimulation', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
status = parseSoapResponse(response);
