/* soapStub.h
   Generated by gSOAP 2.7.6e from IoSteerWS.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_fdata
#define SOAP_TYPE_fdata (6)
/* SOAP encoded array of xsd:double schema type: */
struct fdata
{
public:
	double *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns__addResponse
#define SOAP_TYPE_ns__addResponse (10)
/* ns:addResponse */
struct ns__addResponse
{
public:
	double *result;	/* RPC return element */	/* optional element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_ns__add
#define SOAP_TYPE_ns__add (11)
/* ns:add */
struct ns__add
{
public:
	double a;	/* required element of type xsd:double */
	double b;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_ns__getstepResponse
#define SOAP_TYPE_ns__getstepResponse (14)
/* ns:getstepResponse */
struct ns__getstepResponse
{
public:
	int *step;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getstep
#define SOAP_TYPE_ns__getstep (15)
/* ns:getstep */
struct ns__getstep
{
public:
	int id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setstepResponse
#define SOAP_TYPE_ns__setstepResponse (17)
/* ns:setstepResponse */
struct ns__setstepResponse
{
public:
	int *step;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setstep
#define SOAP_TYPE_ns__setstep (18)
/* ns:setstep */
struct ns__setstep
{
public:
	int id;	/* required element of type xsd:int */
	int newstep;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getnstepsResponse
#define SOAP_TYPE_ns__getnstepsResponse (20)
/* ns:getnstepsResponse */
struct ns__getnstepsResponse
{
public:
	int *nsstep;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getnsteps
#define SOAP_TYPE_ns__getnsteps (21)
/* ns:getnsteps */
struct ns__getnsteps
{
public:
	int id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setnstepsResponse
#define SOAP_TYPE_ns__setnstepsResponse (23)
/* ns:setnstepsResponse */
struct ns__setnstepsResponse
{
public:
	int *nsteps;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setnsteps
#define SOAP_TYPE_ns__setnsteps (24)
/* ns:setnsteps */
struct ns__setnsteps
{
public:
	int id;	/* required element of type xsd:int */
	int newnsteps;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__runsimulationstepResponse
#define SOAP_TYPE_ns__runsimulationstepResponse (26)
/* ns:runsimulationstepResponse */
struct ns__runsimulationstepResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__runsimulationstep
#define SOAP_TYPE_ns__runsimulationstep (27)
/* ns:runsimulationstep */
struct ns__runsimulationstep
{
public:
	int id;	/* required element of type xsd:int */
	int istepnum;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__runsimulationResponse
#define SOAP_TYPE_ns__runsimulationResponse (30)
/* ns:runsimulationResponse */
struct ns__runsimulationResponse
{
public:
	char **result;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__runsimulation
#define SOAP_TYPE_ns__runsimulation (31)
/* ns:runsimulation */
struct ns__runsimulation
{
public:
	int id;	/* required element of type xsd:int */
	char *simfilecontent;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__requestsimulationResponse
#define SOAP_TYPE_ns__requestsimulationResponse (33)
/* ns:requestsimulationResponse */
struct ns__requestsimulationResponse
{
public:
	int *isimid;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__requestsimulation
#define SOAP_TYPE_ns__requestsimulation (34)
/* ns:requestsimulation */
struct ns__requestsimulation
{
public:
	char *simfilecontent;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__runrequestedsimulationResponse
#define SOAP_TYPE_ns__runrequestedsimulationResponse (36)
/* ns:runrequestedsimulationResponse */
struct ns__runrequestedsimulationResponse
{
public:
	int *istatus;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__runrequestedsimulation
#define SOAP_TYPE_ns__runrequestedsimulation (37)
/* ns:runrequestedsimulation */
struct ns__runrequestedsimulation
{
public:
	int isimid;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__submitsimulationResponse
#define SOAP_TYPE_ns__submitsimulationResponse (39)
/* ns:submitsimulationResponse */
struct ns__submitsimulationResponse
{
public:
	int *isimid;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__submitsimulation
#define SOAP_TYPE_ns__submitsimulation (40)
/* ns:submitsimulation */
struct ns__submitsimulation
{
public:
	char *simfilecontent;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__simulationstatusResponse
#define SOAP_TYPE_ns__simulationstatusResponse (42)
/* ns:simulationstatusResponse */
struct ns__simulationstatusResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__simulationstatus
#define SOAP_TYPE_ns__simulationstatus (43)
/* ns:simulationstatus */
struct ns__simulationstatus
{
public:
	int isimid;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setsimulationstatusResponse
#define SOAP_TYPE_ns__setsimulationstatusResponse (45)
/* ns:setsimulationstatusResponse */
struct ns__setsimulationstatusResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setsimulationstatus
#define SOAP_TYPE_ns__setsimulationstatus (46)
/* ns:setsimulationstatus */
struct ns__setsimulationstatus
{
public:
	int newstatus;	/* required element of type xsd:int */
	int isimid;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getsimulationresultsResponse
#define SOAP_TYPE_ns__getsimulationresultsResponse (48)
/* ns:getsimulationresultsResponse */
struct ns__getsimulationresultsResponse
{
public:
	char **result;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__getsimulationresults
#define SOAP_TYPE_ns__getsimulationresults (49)
/* ns:getsimulationresults */
struct ns__getsimulationresults
{
public:
	int isimid;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__deletesimulationResponse
#define SOAP_TYPE_ns__deletesimulationResponse (51)
/* ns:deletesimulationResponse */
struct ns__deletesimulationResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__deletesimulation
#define SOAP_TYPE_ns__deletesimulation (52)
/* ns:deletesimulation */
struct ns__deletesimulation
{
public:
	int isimid;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__newsimulationResponse
#define SOAP_TYPE_ns__newsimulationResponse (54)
/* ns:newsimulationResponse */
struct ns__newsimulationResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__newsimulation
#define SOAP_TYPE_ns__newsimulation (55)
/* ns:newsimulation */
struct ns__newsimulation
{
public:
	int id;	/* required element of type xsd:int */
	char *simname;	/* optional element of type xsd:string */
	char *xslname;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__createsimulationResponse
#define SOAP_TYPE_ns__createsimulationResponse (57)
/* ns:createsimulationResponse */
struct ns__createsimulationResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__createsimulation
#define SOAP_TYPE_ns__createsimulation (58)
/* ns:createsimulation */
struct ns__createsimulation
{
public:
	int id;	/* required element of type xsd:int */
	char *filename;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__writelocalsimulationResponse
#define SOAP_TYPE_ns__writelocalsimulationResponse (60)
/* ns:writelocalsimulationResponse */
struct ns__writelocalsimulationResponse
{
public:
	char **filecontent;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__writelocalsimulation
#define SOAP_TYPE_ns__writelocalsimulation (61)
/* ns:writelocalsimulation */
struct ns__writelocalsimulation
{
public:
	int id;	/* required element of type xsd:int */
	char *filename;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__readlocalsimulationResponse
#define SOAP_TYPE_ns__readlocalsimulationResponse (63)
/* ns:readlocalsimulationResponse */
struct ns__readlocalsimulationResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__readlocalsimulation
#define SOAP_TYPE_ns__readlocalsimulation (64)
/* ns:readlocalsimulation */
struct ns__readlocalsimulation
{
public:
	int id;	/* required element of type xsd:int */
	char *filename;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__writesimulationResponse
#define SOAP_TYPE_ns__writesimulationResponse (66)
/* ns:writesimulationResponse */
struct ns__writesimulationResponse
{
public:
	char **filecontent;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__writesimulation
#define SOAP_TYPE_ns__writesimulation (67)
/* ns:writesimulation */
struct ns__writesimulation
{
public:
	int id;	/* required element of type xsd:int */
	char *filename;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__readsimulationResponse
#define SOAP_TYPE_ns__readsimulationResponse (69)
/* ns:readsimulationResponse */
struct ns__readsimulationResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__readsimulation
#define SOAP_TYPE_ns__readsimulation (70)
/* ns:readsimulation */
struct ns__readsimulation
{
public:
	int id;	/* required element of type xsd:int */
	char *filename;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__exitiomeResponse
#define SOAP_TYPE_ns__exitiomeResponse (72)
/* ns:exitiomeResponse */
struct ns__exitiomeResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__exitiome
#define SOAP_TYPE_ns__exitiome (73)
/* ns:exitiome */
struct ns__exitiome
{
public:
	int id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparamdoubleResponse
#define SOAP_TYPE_ns__addparamdoubleResponse (75)
/* ns:addparamdoubleResponse */
struct ns__addparamdoubleResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparamdouble
#define SOAP_TYPE_ns__addparamdouble (76)
/* ns:addparamdouble */
struct ns__addparamdouble
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	double value;	/* required element of type xsd:double */
	int iflag;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparamintResponse
#define SOAP_TYPE_ns__addparamintResponse (78)
/* ns:addparamintResponse */
struct ns__addparamintResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparamint
#define SOAP_TYPE_ns__addparamint (79)
/* ns:addparamint */
struct ns__addparamint
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	int value;	/* required element of type xsd:int */
	int iflag;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparamvecResponse
#define SOAP_TYPE_ns__addparamvecResponse (81)
/* ns:addparamvecResponse */
struct ns__addparamvecResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparamvec
#define SOAP_TYPE_ns__addparamvec (82)
/* ns:addparamvec */
struct ns__addparamvec
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	struct fdata value;	/* required element of type ArrayOfdouble */
	int n;	/* required element of type xsd:int */
	int iflag;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparammatResponse
#define SOAP_TYPE_ns__addparammatResponse (84)
/* ns:addparammatResponse */
struct ns__addparammatResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparammat
#define SOAP_TYPE_ns__addparammat (85)
/* ns:addparammat */
struct ns__addparammat
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	struct fdata value;	/* required element of type ArrayOfdouble */
	int nr;	/* required element of type xsd:int */
	int nc;	/* required element of type xsd:int */
	int iflag;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparamstringResponse
#define SOAP_TYPE_ns__addparamstringResponse (87)
/* ns:addparamstringResponse */
struct ns__addparamstringResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparamstring
#define SOAP_TYPE_ns__addparamstring (88)
/* ns:addparamstring */
struct ns__addparamstring
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	char *value;	/* optional element of type xsd:string */
	int iflag;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparammmat3dResponse
#define SOAP_TYPE_ns__addparammmat3dResponse (90)
/* ns:addparammmat3dResponse */
struct ns__addparammmat3dResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addparammmat3d
#define SOAP_TYPE_ns__addparammmat3d (91)
/* ns:addparammmat3d */
struct ns__addparammmat3d
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	struct fdata value;	/* required element of type ArrayOfdouble */
	int n;	/* required element of type xsd:int */
	int p;	/* required element of type xsd:int */
	int q;	/* required element of type xsd:int */
	int nr;	/* required element of type xsd:int */
	int nc;	/* required element of type xsd:int */
	int iflag;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addmetadataResponse
#define SOAP_TYPE_ns__addmetadataResponse (93)
/* ns:addmetadataResponse */
struct ns__addmetadataResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__addmetadata
#define SOAP_TYPE_ns__addmetadata (94)
/* ns:addmetadata */
struct ns__addmetadata
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	char *property;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__getparamdoubleResponse
#define SOAP_TYPE_ns__getparamdoubleResponse (96)
/* ns:getparamdoubleResponse */
struct ns__getparamdoubleResponse
{
public:
	double *value;	/* RPC return element */	/* optional element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_ns__getparamdouble
#define SOAP_TYPE_ns__getparamdouble (97)
/* ns:getparamdouble */
struct ns__getparamdouble
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__getparamintResponse
#define SOAP_TYPE_ns__getparamintResponse (99)
/* ns:getparamintResponse */
struct ns__getparamintResponse
{
public:
	int *value;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getparamint
#define SOAP_TYPE_ns__getparamint (100)
/* ns:getparamint */
struct ns__getparamint
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__getparamvecResponse
#define SOAP_TYPE_ns__getparamvecResponse (104)
/* ns:getparamvecResponse */
struct ns__getparamvecResponse
{
public:
	struct fdata **dval;	/* RPC return element */	/* optional element of type ArrayOfdouble */
};
#endif

#ifndef SOAP_TYPE_ns__getparamvec
#define SOAP_TYPE_ns__getparamvec (105)
/* ns:getparamvec */
struct ns__getparamvec
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	int n;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getparammatResponse
#define SOAP_TYPE_ns__getparammatResponse (107)
/* ns:getparammatResponse */
struct ns__getparammatResponse
{
public:
	struct fdata **dval;	/* RPC return element */	/* optional element of type ArrayOfdouble */
};
#endif

#ifndef SOAP_TYPE_ns__getparammat
#define SOAP_TYPE_ns__getparammat (108)
/* ns:getparammat */
struct ns__getparammat
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	int nr;	/* required element of type xsd:int */
	int nc;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getparamstringResponse
#define SOAP_TYPE_ns__getparamstringResponse (110)
/* ns:getparamstringResponse */
struct ns__getparamstringResponse
{
public:
	char **value;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__getparamstring
#define SOAP_TYPE_ns__getparamstring (111)
/* ns:getparamstring */
struct ns__getparamstring
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__getparammmat3dResponse
#define SOAP_TYPE_ns__getparammmat3dResponse (113)
/* ns:getparammmat3dResponse */
struct ns__getparammmat3dResponse
{
public:
	struct fdata **mmat3d;	/* RPC return element */	/* optional element of type ArrayOfdouble */
};
#endif

#ifndef SOAP_TYPE_ns__getparammmat3d
#define SOAP_TYPE_ns__getparammmat3d (114)
/* ns:getparammmat3d */
struct ns__getparammmat3d
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	int n;	/* required element of type xsd:int */
	int p;	/* required element of type xsd:int */
	int q;	/* required element of type xsd:int */
	int nr;	/* required element of type xsd:int */
	int nc;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getmetadataResponse
#define SOAP_TYPE_ns__getmetadataResponse (116)
/* ns:getmetadataResponse */
struct ns__getmetadataResponse
{
public:
	char **property;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__getmetadata
#define SOAP_TYPE_ns__getmetadata (117)
/* ns:getmetadata */
struct ns__getmetadata
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__setparamdoubleResponse
#define SOAP_TYPE_ns__setparamdoubleResponse (119)
/* ns:setparamdoubleResponse */
struct ns__setparamdoubleResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setparamdouble
#define SOAP_TYPE_ns__setparamdouble (120)
/* ns:setparamdouble */
struct ns__setparamdouble
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	double value;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_ns__setparamintResponse
#define SOAP_TYPE_ns__setparamintResponse (122)
/* ns:setparamintResponse */
struct ns__setparamintResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setparamint
#define SOAP_TYPE_ns__setparamint (123)
/* ns:setparamint */
struct ns__setparamint
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	int value;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setparamvecResponse
#define SOAP_TYPE_ns__setparamvecResponse (125)
/* ns:setparamvecResponse */
struct ns__setparamvecResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setparamvec
#define SOAP_TYPE_ns__setparamvec (126)
/* ns:setparamvec */
struct ns__setparamvec
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	struct fdata value;	/* required element of type ArrayOfdouble */
	int n;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setparammatResponse
#define SOAP_TYPE_ns__setparammatResponse (128)
/* ns:setparammatResponse */
struct ns__setparammatResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setparammat
#define SOAP_TYPE_ns__setparammat (129)
/* ns:setparammat */
struct ns__setparammat
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	struct fdata value;	/* required element of type ArrayOfdouble */
	int nr;	/* required element of type xsd:int */
	int nc;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setparamstringResponse
#define SOAP_TYPE_ns__setparamstringResponse (131)
/* ns:setparamstringResponse */
struct ns__setparamstringResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setparamstring
#define SOAP_TYPE_ns__setparamstring (132)
/* ns:setparamstring */
struct ns__setparamstring
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	char *value;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__setparammmat3dResponse
#define SOAP_TYPE_ns__setparammmat3dResponse (134)
/* ns:setparammmat3dResponse */
struct ns__setparammmat3dResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setparammmat3d
#define SOAP_TYPE_ns__setparammmat3d (135)
/* ns:setparammmat3d */
struct ns__setparammmat3d
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	struct fdata value;	/* required element of type ArrayOfdouble */
	int n;	/* required element of type xsd:int */
	int p;	/* required element of type xsd:int */
	int q;	/* required element of type xsd:int */
	int nr;	/* required element of type xsd:int */
	int nc;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setmetadataResponse
#define SOAP_TYPE_ns__setmetadataResponse (137)
/* ns:setmetadataResponse */
struct ns__setmetadataResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setmetadata
#define SOAP_TYPE_ns__setmetadata (138)
/* ns:setmetadata */
struct ns__setmetadata
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
	char *property;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__listmetadataResponse
#define SOAP_TYPE_ns__listmetadataResponse (140)
/* ns:listmetadataResponse */
struct ns__listmetadataResponse
{
public:
	char **list;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__listmetadata
#define SOAP_TYPE_ns__listmetadata (141)
/* ns:listmetadata */
struct ns__listmetadata
{
public:
	int id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__deletemetadataResponse
#define SOAP_TYPE_ns__deletemetadataResponse (143)
/* ns:deletemetadataResponse */
struct ns__deletemetadataResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__deletemetadata
#define SOAP_TYPE_ns__deletemetadata (144)
/* ns:deletemetadata */
struct ns__deletemetadata
{
public:
	int id;	/* required element of type xsd:int */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__deleteparamResponse
#define SOAP_TYPE_ns__deleteparamResponse (146)
/* ns:deleteparamResponse */
struct ns__deleteparamResponse
{
public:
	int *status;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__deleteparam
#define SOAP_TYPE_ns__deleteparam (147)
/* ns:deleteparam */
struct ns__deleteparam
{
public:
	char *name;	/* optional element of type xsd:string */
	int id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__listparamResponse
#define SOAP_TYPE_ns__listparamResponse (149)
/* ns:listparamResponse */
struct ns__listparamResponse
{
public:
	char **list;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__listparam
#define SOAP_TYPE_ns__listparam (150)
/* ns:listparam */
struct ns__listparam
{
public:
	char *type;	/* optional element of type xsd:string */
	int id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getnumobjResponse
#define SOAP_TYPE_ns__getnumobjResponse (152)
/* ns:getnumobjResponse */
struct ns__getnumobjResponse
{
public:
	int *numobj;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getnumobj
#define SOAP_TYPE_ns__getnumobj (153)
/* ns:getnumobj */
struct ns__getnumobj
{
public:
	int id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getobjnumResponse
#define SOAP_TYPE_ns__getobjnumResponse (155)
/* ns:getobjnumResponse */
struct ns__getobjnumResponse
{
public:
	int *objnum;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__getobjnum
#define SOAP_TYPE_ns__getobjnum (156)
/* ns:getobjnum */
struct ns__getobjnum
{
public:
	int id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__testgroupbarrierResponse
#define SOAP_TYPE_ns__testgroupbarrierResponse (158)
/* ns:testgroupbarrierResponse */
struct ns__testgroupbarrierResponse
{
public:
	int *state;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__testgroupbarrier
#define SOAP_TYPE_ns__testgroupbarrier (159)
/* ns:testgroupbarrier */
struct ns__testgroupbarrier
{
public:
	int id;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setgroupbarrierResponse
#define SOAP_TYPE_ns__setgroupbarrierResponse (161)
/* ns:setgroupbarrierResponse */
struct ns__setgroupbarrierResponse
{
public:
	int *newstate;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setgroupbarrier
#define SOAP_TYPE_ns__setgroupbarrier (162)
/* ns:setgroupbarrier */
struct ns__setgroupbarrier
{
public:
	int id;	/* required element of type xsd:int */
	int state;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (165)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	void *dummy;	/* transient */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (166)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (168)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (169)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (170)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns__add(struct soap*, double a, double b, double *result);

SOAP_FMAC5 int SOAP_FMAC6 ns__getstep(struct soap*, int id, int *step);

SOAP_FMAC5 int SOAP_FMAC6 ns__setstep(struct soap*, int id, int newstep, int *step);

SOAP_FMAC5 int SOAP_FMAC6 ns__getnsteps(struct soap*, int id, int *nsstep);

SOAP_FMAC5 int SOAP_FMAC6 ns__setnsteps(struct soap*, int id, int newnsteps, int *nsteps);

SOAP_FMAC5 int SOAP_FMAC6 ns__runsimulationstep(struct soap*, int id, int istepnum, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__runsimulation(struct soap*, int id, char *simfilecontent, char **result);

SOAP_FMAC5 int SOAP_FMAC6 ns__requestsimulation(struct soap*, char *simfilecontent, int *isimid);

SOAP_FMAC5 int SOAP_FMAC6 ns__runrequestedsimulation(struct soap*, int isimid, int *istatus);

SOAP_FMAC5 int SOAP_FMAC6 ns__submitsimulation(struct soap*, char *simfilecontent, int *isimid);

SOAP_FMAC5 int SOAP_FMAC6 ns__simulationstatus(struct soap*, int isimid, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__setsimulationstatus(struct soap*, int newstatus, int isimid, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__getsimulationresults(struct soap*, int isimid, char **result);

SOAP_FMAC5 int SOAP_FMAC6 ns__deletesimulation(struct soap*, int isimid, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__newsimulation(struct soap*, int id, char *simname, char *xslname, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__createsimulation(struct soap*, int id, char *filename, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__writelocalsimulation(struct soap*, int id, char *filename, char **filecontent);

SOAP_FMAC5 int SOAP_FMAC6 ns__readlocalsimulation(struct soap*, int id, char *filename, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__writesimulation(struct soap*, int id, char *filename, char **filecontent);

SOAP_FMAC5 int SOAP_FMAC6 ns__readsimulation(struct soap*, int id, char *filename, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__exitiome(struct soap*, int id, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__addparamdouble(struct soap*, int id, char *name, double value, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__addparamint(struct soap*, int id, char *name, int value, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__addparamvec(struct soap*, int id, char *name, struct fdata value, int n, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__addparammat(struct soap*, int id, char *name, struct fdata value, int nr, int nc, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__addparamstring(struct soap*, int id, char *name, char *value, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__addparammmat3d(struct soap*, int id, char *name, struct fdata value, int n, int p, int q, int nr, int nc, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__addmetadata(struct soap*, int id, char *name, char *property, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__getparamdouble(struct soap*, int id, char *name, double *value);

SOAP_FMAC5 int SOAP_FMAC6 ns__getparamint(struct soap*, int id, char *name, int *value);

SOAP_FMAC5 int SOAP_FMAC6 ns__getparamvec(struct soap*, int id, char *name, int n, struct fdata **dval);

SOAP_FMAC5 int SOAP_FMAC6 ns__getparammat(struct soap*, int id, char *name, int nr, int nc, struct fdata **dval);

SOAP_FMAC5 int SOAP_FMAC6 ns__getparamstring(struct soap*, int id, char *name, char **value);

SOAP_FMAC5 int SOAP_FMAC6 ns__getparammmat3d(struct soap*, int id, char *name, int n, int p, int q, int nr, int nc, struct fdata **mmat3d);

SOAP_FMAC5 int SOAP_FMAC6 ns__getmetadata(struct soap*, int id, char *name, char **property);

SOAP_FMAC5 int SOAP_FMAC6 ns__setparamdouble(struct soap*, int id, char *name, double value, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__setparamint(struct soap*, int id, char *name, int value, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__setparamvec(struct soap*, int id, char *name, struct fdata value, int n, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__setparammat(struct soap*, int id, char *name, struct fdata value, int nr, int nc, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__setparamstring(struct soap*, int id, char *name, char *value, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__setparammmat3d(struct soap*, int id, char *name, struct fdata value, int n, int p, int q, int nr, int nc, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__setmetadata(struct soap*, int id, char *name, char *property, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__listmetadata(struct soap*, int id, char **list);

SOAP_FMAC5 int SOAP_FMAC6 ns__deletemetadata(struct soap*, int id, char *name, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__deleteparam(struct soap*, char *name, int id, int *status);

SOAP_FMAC5 int SOAP_FMAC6 ns__listparam(struct soap*, char *type, int id, char **list);

SOAP_FMAC5 int SOAP_FMAC6 ns__getnumobj(struct soap*, int id, int *numobj);

SOAP_FMAC5 int SOAP_FMAC6 ns__getobjnum(struct soap*, int id, int *objnum);

SOAP_FMAC5 int SOAP_FMAC6 ns__testgroupbarrier(struct soap*, int id, int *state);

SOAP_FMAC5 int SOAP_FMAC6 ns__setgroupbarrier(struct soap*, int id, int state, int *newstate);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__add(struct soap *soap, const char *soap_endpoint, const char *soap_action, double a, double b, double *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getstep(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int *step);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setstep(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int newstep, int *step);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getnsteps(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int *nsstep);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setnsteps(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int newnsteps, int *nsteps);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__runsimulationstep(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int istepnum, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__runsimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *simfilecontent, char **result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__requestsimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *simfilecontent, int *isimid);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__runrequestedsimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, int isimid, int *istatus);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__submitsimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *simfilecontent, int *isimid);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__simulationstatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, int isimid, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setsimulationstatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, int newstatus, int isimid, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getsimulationresults(struct soap *soap, const char *soap_endpoint, const char *soap_action, int isimid, char **result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__deletesimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, int isimid, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__newsimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *simname, char *xslname, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__createsimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *filename, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__writelocalsimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *filename, char **filecontent);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__readlocalsimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *filename, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__writesimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *filename, char **filecontent);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__readsimulation(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *filename, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__exitiome(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__addparamdouble(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, double value, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__addparamint(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, int value, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__addparamvec(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, struct fdata value, int n, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__addparammat(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, struct fdata value, int nr, int nc, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__addparamstring(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, char *value, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__addparammmat3d(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, struct fdata value, int n, int p, int q, int nr, int nc, int iflag, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__addmetadata(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, char *property, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getparamdouble(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, double *value);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getparamint(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, int *value);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getparamvec(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, int n, struct fdata **dval);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getparammat(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, int nr, int nc, struct fdata **dval);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getparamstring(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, char **value);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getparammmat3d(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, int n, int p, int q, int nr, int nc, struct fdata **mmat3d);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getmetadata(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, char **property);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setparamdouble(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, double value, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setparamint(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, int value, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setparamvec(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, struct fdata value, int n, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setparammat(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, struct fdata value, int nr, int nc, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setparamstring(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, char *value, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setparammmat3d(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, struct fdata value, int n, int p, int q, int nr, int nc, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setmetadata(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, char *property, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__listmetadata(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char **list);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__deletemetadata(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *name, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__deleteparam(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *name, int id, int *status);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__listparam(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *type, int id, char **list);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getnumobj(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int *numobj);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getobjnum(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int *objnum);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__testgroupbarrier(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int *state);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setgroupbarrier(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int state, int *newstate);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__add(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getstep(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setstep(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getnsteps(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setnsteps(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__runsimulationstep(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__runsimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__requestsimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__runrequestedsimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__submitsimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__simulationstatus(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setsimulationstatus(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getsimulationresults(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__deletesimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__newsimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__createsimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__writelocalsimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__readlocalsimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__writesimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__readsimulation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__exitiome(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparamdouble(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparamint(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparamvec(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparammat(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparamstring(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addparammmat3d(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__addmetadata(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparamdouble(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparamint(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparamvec(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparammat(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparamstring(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getparammmat3d(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getmetadata(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparamdouble(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparamint(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparamvec(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparammat(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparamstring(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setparammmat3d(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setmetadata(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__listmetadata(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__deletemetadata(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__deleteparam(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__listparam(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getnumobj(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getobjnum(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__testgroupbarrier(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setgroupbarrier(struct soap*);

#endif

/* End of soapStub.h */
