function value = getparamstring(obj,id,name)
%getparamstring(obj,id,name)
%
%   Service definition of function ns__getparamstring
%   
%     Input:
%       id = (int)
%       name = (string)
%   
%     Output:
%       value = (string)

% Build up the argument lists.
values = { ...
   id, ...
   name, ...
   };
names = { ...
   'id', ...
   'name', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'getparamstring', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
value = parseSoapResponse(response);
