function result = getsimulationresults(obj,isimid)
%getsimulationresults(obj,isimid)
%
%   Service definition of function ns__getsimulationresults
%   
%     Input:
%       isimid = (int)
%   
%     Output:
%       result = (string)

% Build up the argument lists.
values = { ...
   isimid, ...
   };
names = { ...
   'isimid', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'getsimulationresults', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
result = parseSoapResponse(response);
