function list = listmetadata(obj,id)
%listmetadata(obj,id)
%
%   Service definition of function ns__listmetadata
%   
%     Input:
%       id = (int)
%   
%     Output:
%       list = (string)

% Build up the argument lists.
values = { ...
   id, ...
   };
names = { ...
   'id', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'listmetadata', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
list = parseSoapResponse(response);
