iophp.lo: /home/cs1mkg/proj/iome2_2_1/IoGenericSimulationPHPauto/iophp.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/cs1mkg/proj/iome2_2_1/IoGenericSimulationPHPauto $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/cs1mkg/proj/iome2_2_1/IoGenericSimulationPHPauto/iophp.c -o iophp.lo 
$(phplibdir)/iophp.la: ./iophp.la
	$(LIBTOOL) --mode=install cp ./iophp.la $(phplibdir)

./iophp.la: $(shared_objects_iophp) $(IOPHP_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_iophp) $(IOPHP_SHARED_LIBADD)

