function isimid = submitsimulation(obj,simfilecontent)
%submitsimulation(obj,simfilecontent)
%
%   Service definition of function ns__submitsimulation
%   
%     Input:
%       simfilecontent = (string)
%   
%     Output:
%       isimid = (int)

% Build up the argument lists.
values = { ...
   simfilecontent, ...
   };
names = { ...
   'simfilecontent', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'submitsimulation', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
isimid = parseSoapResponse(response);
