function filecontent = writelocalsimulation(obj,id,filename)
%writelocalsimulation(obj,id,filename)
%
%   Service definition of function ns__writelocalsimulation
%   
%     Input:
%       id = (int)
%       filename = (string)
%   
%     Output:
%       filecontent = (string)

% Build up the argument lists.
values = { ...
   id, ...
   filename, ...
   };
names = { ...
   'id', ...
   'filename', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'writelocalsimulation', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
filecontent = parseSoapResponse(response);
