function status = addmetadata(obj,id,name,property)
%addmetadata(obj,id,name,property)
%
%   Service definition of function ns__addmetadata
%   
%     Input:
%       id = (int)
%       name = (string)
%       property = (string)
%   
%     Output:
%       status = (int)

% Build up the argument lists.
values = { ...
   id, ...
   name, ...
   property, ...
   };
names = { ...
   'id', ...
   'name', ...
   'property', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'addmetadata', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
status = parseSoapResponse(response);
