function nsstep = getnsteps(obj,id)
%getnsteps(obj,id)
%
%   Service definition of function ns__getnsteps
%   
%     Input:
%       id = (int)
%   
%     Output:
%       nsstep = (int)

% Build up the argument lists.
values = { ...
   id, ...
   };
names = { ...
   'id', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'getnsteps', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
nsstep = parseSoapResponse(response);
