function newstate = setgroupbarrier(obj,id,state)
%setgroupbarrier(obj,id,state)
%
%   Service definition of function ns__setgroupbarrier
%   
%     Input:
%       id = (int)
%       state = (int)
%   
%     Output:
%       newstate = (int)

% Build up the argument lists.
values = { ...
   id, ...
   state, ...
   };
names = { ...
   'id', ...
   'state', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'setgroupbarrier', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
newstate = parseSoapResponse(response);
