##################################################
# file: IoSteerWS_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      C:\Python25\Scripts\wsdl2py-script.py ..\..\IoSimulation\IoSteerWS.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from IoSteerWS_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
class addRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        a -- part a
        b -- part b
        """
        self._a =  kw.get("a")
        self._b =  kw.get("b")
addRequest.typecode = Struct(pname=("urn:IoSteerWS","add"), ofwhat=[ZSI.TCnumbers.FPdouble(pname="a", aname="_a", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPdouble(pname="b", aname="_b", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addRequest, encoded="urn:IoSteerWS")

class addResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        result -- part result
        """
        self._result =  kw.get("result")
addResponse.typecode = Struct(pname=("urn:IoSteerWS","addResponse"), ofwhat=[ZSI.TCnumbers.FPdouble(pname="result", aname="_result", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addResponse, encoded="urn:IoSteerWS")

class getstepRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        """
        self._id =  kw.get("id")
getstepRequest.typecode = Struct(pname=("urn:IoSteerWS","getstep"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getstepRequest, encoded="urn:IoSteerWS")

class getstepResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        step -- part step
        """
        self._step =  kw.get("step")
getstepResponse.typecode = Struct(pname=("urn:IoSteerWS","getstepResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="step", aname="_step", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getstepResponse, encoded="urn:IoSteerWS")

class setstepRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        newstep -- part newstep
        """
        self._id =  kw.get("id")
        self._newstep =  kw.get("newstep")
setstepRequest.typecode = Struct(pname=("urn:IoSteerWS","setstep"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="newstep", aname="_newstep", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setstepRequest, encoded="urn:IoSteerWS")

class setstepResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        step -- part step
        """
        self._step =  kw.get("step")
setstepResponse.typecode = Struct(pname=("urn:IoSteerWS","setstepResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="step", aname="_step", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setstepResponse, encoded="urn:IoSteerWS")

class getnstepsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        """
        self._id =  kw.get("id")
getnstepsRequest.typecode = Struct(pname=("urn:IoSteerWS","getnsteps"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getnstepsRequest, encoded="urn:IoSteerWS")

class getnstepsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        nsstep -- part nsstep
        """
        self._nsstep =  kw.get("nsstep")
getnstepsResponse.typecode = Struct(pname=("urn:IoSteerWS","getnstepsResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="nsstep", aname="_nsstep", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getnstepsResponse, encoded="urn:IoSteerWS")

class setnstepsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        newnsteps -- part newnsteps
        """
        self._id =  kw.get("id")
        self._newnsteps =  kw.get("newnsteps")
setnstepsRequest.typecode = Struct(pname=("urn:IoSteerWS","setnsteps"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="newnsteps", aname="_newnsteps", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setnstepsRequest, encoded="urn:IoSteerWS")

class setnstepsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        nsteps -- part nsteps
        """
        self._nsteps =  kw.get("nsteps")
setnstepsResponse.typecode = Struct(pname=("urn:IoSteerWS","setnstepsResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="nsteps", aname="_nsteps", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setnstepsResponse, encoded="urn:IoSteerWS")

class runsimulationstepRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        istepnum -- part istepnum
        """
        self._id =  kw.get("id")
        self._istepnum =  kw.get("istepnum")
runsimulationstepRequest.typecode = Struct(pname=("urn:IoSteerWS","runsimulationstep"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="istepnum", aname="_istepnum", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=runsimulationstepRequest, encoded="urn:IoSteerWS")

class runsimulationstepResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
runsimulationstepResponse.typecode = Struct(pname=("urn:IoSteerWS","runsimulationstepResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=runsimulationstepResponse, encoded="urn:IoSteerWS")

class runsimulationRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        simfilecontent -- part simfilecontent
        """
        self._id =  kw.get("id")
        self._simfilecontent =  kw.get("simfilecontent")
runsimulationRequest.typecode = Struct(pname=("urn:IoSteerWS","runsimulation"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="simfilecontent", aname="_simfilecontent", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=runsimulationRequest, encoded="urn:IoSteerWS")

class runsimulationResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        result -- part result
        """
        self._result =  kw.get("result")
runsimulationResponse.typecode = Struct(pname=("urn:IoSteerWS","runsimulationResponse"), ofwhat=[ZSI.TC.String(pname="result", aname="_result", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=runsimulationResponse, encoded="urn:IoSteerWS")

class submitsimulationRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        simfilecontent -- part simfilecontent
        """
        self._simfilecontent =  kw.get("simfilecontent")
submitsimulationRequest.typecode = Struct(pname=("urn:IoSteerWS","submitsimulation"), ofwhat=[ZSI.TC.String(pname="simfilecontent", aname="_simfilecontent", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=submitsimulationRequest, encoded="urn:IoSteerWS")

class submitsimulationResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        isimid -- part isimid
        """
        self._isimid =  kw.get("isimid")
submitsimulationResponse.typecode = Struct(pname=("urn:IoSteerWS","submitsimulationResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="isimid", aname="_isimid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=submitsimulationResponse, encoded="urn:IoSteerWS")

class simulationstatusRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        isimid -- part isimid
        """
        self._isimid =  kw.get("isimid")
simulationstatusRequest.typecode = Struct(pname=("urn:IoSteerWS","simulationstatus"), ofwhat=[ZSI.TCnumbers.Iint(pname="isimid", aname="_isimid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=simulationstatusRequest, encoded="urn:IoSteerWS")

class simulationstatusResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
simulationstatusResponse.typecode = Struct(pname=("urn:IoSteerWS","simulationstatusResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=simulationstatusResponse, encoded="urn:IoSteerWS")

class getsimulationresultsRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        isimid -- part isimid
        """
        self._isimid =  kw.get("isimid")
getsimulationresultsRequest.typecode = Struct(pname=("urn:IoSteerWS","getsimulationresults"), ofwhat=[ZSI.TCnumbers.Iint(pname="isimid", aname="_isimid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getsimulationresultsRequest, encoded="urn:IoSteerWS")

class getsimulationresultsResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        result -- part result
        """
        self._result =  kw.get("result")
getsimulationresultsResponse.typecode = Struct(pname=("urn:IoSteerWS","getsimulationresultsResponse"), ofwhat=[ZSI.TC.String(pname="result", aname="_result", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getsimulationresultsResponse, encoded="urn:IoSteerWS")

class deletesimulationRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        isimid -- part isimid
        """
        self._isimid =  kw.get("isimid")
deletesimulationRequest.typecode = Struct(pname=("urn:IoSteerWS","deletesimulation"), ofwhat=[ZSI.TCnumbers.Iint(pname="isimid", aname="_isimid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=deletesimulationRequest, encoded="urn:IoSteerWS")

class deletesimulationResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
deletesimulationResponse.typecode = Struct(pname=("urn:IoSteerWS","deletesimulationResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=deletesimulationResponse, encoded="urn:IoSteerWS")

class newsimulationRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        simname -- part simname
        xslname -- part xslname
        """
        self._id =  kw.get("id")
        self._simname =  kw.get("simname")
        self._xslname =  kw.get("xslname")
newsimulationRequest.typecode = Struct(pname=("urn:IoSteerWS","newsimulation"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="simname", aname="_simname", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="xslname", aname="_xslname", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=newsimulationRequest, encoded="urn:IoSteerWS")

class newsimulationResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
newsimulationResponse.typecode = Struct(pname=("urn:IoSteerWS","newsimulationResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=newsimulationResponse, encoded="urn:IoSteerWS")

class createsimulationRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        filename -- part filename
        """
        self._id =  kw.get("id")
        self._filename =  kw.get("filename")
createsimulationRequest.typecode = Struct(pname=("urn:IoSteerWS","createsimulation"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="filename", aname="_filename", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=createsimulationRequest, encoded="urn:IoSteerWS")

class createsimulationResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
createsimulationResponse.typecode = Struct(pname=("urn:IoSteerWS","createsimulationResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=createsimulationResponse, encoded="urn:IoSteerWS")

class writesimulationRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        filename -- part filename
        """
        self._id =  kw.get("id")
        self._filename =  kw.get("filename")
writesimulationRequest.typecode = Struct(pname=("urn:IoSteerWS","writesimulation"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="filename", aname="_filename", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=writesimulationRequest, encoded="urn:IoSteerWS")

class writesimulationResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        filecontent -- part filecontent
        """
        self._filecontent =  kw.get("filecontent")
writesimulationResponse.typecode = Struct(pname=("urn:IoSteerWS","writesimulationResponse"), ofwhat=[ZSI.TC.String(pname="filecontent", aname="_filecontent", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=writesimulationResponse, encoded="urn:IoSteerWS")

class readsimulationRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        filename -- part filename
        """
        self._id =  kw.get("id")
        self._filename =  kw.get("filename")
readsimulationRequest.typecode = Struct(pname=("urn:IoSteerWS","readsimulation"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="filename", aname="_filename", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=readsimulationRequest, encoded="urn:IoSteerWS")

class readsimulationResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
readsimulationResponse.typecode = Struct(pname=("urn:IoSteerWS","readsimulationResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=readsimulationResponse, encoded="urn:IoSteerWS")

class exitiomeRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        """
        self._id =  kw.get("id")
exitiomeRequest.typecode = Struct(pname=("urn:IoSteerWS","exitiome"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=exitiomeRequest, encoded="urn:IoSteerWS")

class exitiomeResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
exitiomeResponse.typecode = Struct(pname=("urn:IoSteerWS","exitiomeResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=exitiomeResponse, encoded="urn:IoSteerWS")

class addparamdoubleRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        iflag -- part iflag
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
        self._iflag =  kw.get("iflag")
addparamdoubleRequest.typecode = Struct(pname=("urn:IoSteerWS","addparamdouble"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPdouble(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="iflag", aname="_iflag", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparamdoubleRequest, encoded="urn:IoSteerWS")

class addparamdoubleResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
addparamdoubleResponse.typecode = Struct(pname=("urn:IoSteerWS","addparamdoubleResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparamdoubleResponse, encoded="urn:IoSteerWS")

class addparamintRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        iflag -- part iflag
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
        self._iflag =  kw.get("iflag")
addparamintRequest.typecode = Struct(pname=("urn:IoSteerWS","addparamint"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="iflag", aname="_iflag", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparamintRequest, encoded="urn:IoSteerWS")

class addparamintResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
addparamintResponse.typecode = Struct(pname=("urn:IoSteerWS","addparamintResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparamintResponse, encoded="urn:IoSteerWS")

class addparamvecRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        n -- part n
        iflag -- part iflag
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
        self._n =  kw.get("n")
        self._iflag =  kw.get("iflag")
addparamvecRequest.typecode = Struct(pname=("urn:IoSteerWS","addparamvec"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.ArrayOfdouble_Def(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="n", aname="_n", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="iflag", aname="_iflag", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparamvecRequest, encoded="urn:IoSteerWS")

class addparamvecResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
addparamvecResponse.typecode = Struct(pname=("urn:IoSteerWS","addparamvecResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparamvecResponse, encoded="urn:IoSteerWS")

class addparammatRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        nr -- part nr
        nc -- part nc
        iflag -- part iflag
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
        self._nr =  kw.get("nr")
        self._nc =  kw.get("nc")
        self._iflag =  kw.get("iflag")
addparammatRequest.typecode = Struct(pname=("urn:IoSteerWS","addparammat"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.ArrayOfdouble_Def(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nr", aname="_nr", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nc", aname="_nc", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="iflag", aname="_iflag", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparammatRequest, encoded="urn:IoSteerWS")

class addparammatResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
addparammatResponse.typecode = Struct(pname=("urn:IoSteerWS","addparammatResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparammatResponse, encoded="urn:IoSteerWS")

class addparamstringRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        iflag -- part iflag
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
        self._iflag =  kw.get("iflag")
addparamstringRequest.typecode = Struct(pname=("urn:IoSteerWS","addparamstring"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="iflag", aname="_iflag", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparamstringRequest, encoded="urn:IoSteerWS")

class addparamstringResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
addparamstringResponse.typecode = Struct(pname=("urn:IoSteerWS","addparamstringResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparamstringResponse, encoded="urn:IoSteerWS")

class addparammmat3dRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        n -- part n
        p -- part p
        q -- part q
        nr -- part nr
        nc -- part nc
        iflag -- part iflag
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
        self._n =  kw.get("n")
        self._p =  kw.get("p")
        self._q =  kw.get("q")
        self._nr =  kw.get("nr")
        self._nc =  kw.get("nc")
        self._iflag =  kw.get("iflag")
addparammmat3dRequest.typecode = Struct(pname=("urn:IoSteerWS","addparammmat3d"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.ArrayOfdouble_Def(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="n", aname="_n", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="p", aname="_p", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="q", aname="_q", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nr", aname="_nr", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nc", aname="_nc", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="iflag", aname="_iflag", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparammmat3dRequest, encoded="urn:IoSteerWS")

class addparammmat3dResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
addparammmat3dResponse.typecode = Struct(pname=("urn:IoSteerWS","addparammmat3dResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addparammmat3dResponse, encoded="urn:IoSteerWS")

class addmetadataRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        property -- part property
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._property =  kw.get("property")
addmetadataRequest.typecode = Struct(pname=("urn:IoSteerWS","addmetadata"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="property", aname="_property", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addmetadataRequest, encoded="urn:IoSteerWS")

class addmetadataResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
addmetadataResponse.typecode = Struct(pname=("urn:IoSteerWS","addmetadataResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=addmetadataResponse, encoded="urn:IoSteerWS")

class getparamdoubleRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
getparamdoubleRequest.typecode = Struct(pname=("urn:IoSteerWS","getparamdouble"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparamdoubleRequest, encoded="urn:IoSteerWS")

class getparamdoubleResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        value -- part value
        """
        self._value =  kw.get("value")
getparamdoubleResponse.typecode = Struct(pname=("urn:IoSteerWS","getparamdoubleResponse"), ofwhat=[ZSI.TCnumbers.FPdouble(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparamdoubleResponse, encoded="urn:IoSteerWS")

class getparamintRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
getparamintRequest.typecode = Struct(pname=("urn:IoSteerWS","getparamint"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparamintRequest, encoded="urn:IoSteerWS")

class getparamintResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        value -- part value
        """
        self._value =  kw.get("value")
getparamintResponse.typecode = Struct(pname=("urn:IoSteerWS","getparamintResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparamintResponse, encoded="urn:IoSteerWS")

class getparamvecRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        n -- part n
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._n =  kw.get("n")
getparamvecRequest.typecode = Struct(pname=("urn:IoSteerWS","getparamvec"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="n", aname="_n", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparamvecRequest, encoded="urn:IoSteerWS")

class getparamvecResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        dval -- part dval
        """
        self._dval =  kw.get("dval")
getparamvecResponse.typecode = Struct(pname=("urn:IoSteerWS","getparamvecResponse"), ofwhat=[ns0.ArrayOfdouble_Def(pname="dval", aname="_dval", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparamvecResponse, encoded="urn:IoSteerWS")

class getparammatRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        nr -- part nr
        nc -- part nc
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._nr =  kw.get("nr")
        self._nc =  kw.get("nc")
getparammatRequest.typecode = Struct(pname=("urn:IoSteerWS","getparammat"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nr", aname="_nr", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nc", aname="_nc", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparammatRequest, encoded="urn:IoSteerWS")

class getparammatResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        dval -- part dval
        """
        self._dval =  kw.get("dval")
getparammatResponse.typecode = Struct(pname=("urn:IoSteerWS","getparammatResponse"), ofwhat=[ns0.ArrayOfdouble_Def(pname="dval", aname="_dval", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparammatResponse, encoded="urn:IoSteerWS")

class getparamstringRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
getparamstringRequest.typecode = Struct(pname=("urn:IoSteerWS","getparamstring"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparamstringRequest, encoded="urn:IoSteerWS")

class getparamstringResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        value -- part value
        """
        self._value =  kw.get("value")
getparamstringResponse.typecode = Struct(pname=("urn:IoSteerWS","getparamstringResponse"), ofwhat=[ZSI.TC.String(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparamstringResponse, encoded="urn:IoSteerWS")

class getparammmat3dRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        n -- part n
        p -- part p
        q -- part q
        nr -- part nr
        nc -- part nc
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._n =  kw.get("n")
        self._p =  kw.get("p")
        self._q =  kw.get("q")
        self._nr =  kw.get("nr")
        self._nc =  kw.get("nc")
getparammmat3dRequest.typecode = Struct(pname=("urn:IoSteerWS","getparammmat3d"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="n", aname="_n", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="p", aname="_p", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="q", aname="_q", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nr", aname="_nr", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nc", aname="_nc", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparammmat3dRequest, encoded="urn:IoSteerWS")

class getparammmat3dResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        mmat3d -- part mmat3d
        """
        self._mmat3d =  kw.get("mmat3d")
getparammmat3dResponse.typecode = Struct(pname=("urn:IoSteerWS","getparammmat3dResponse"), ofwhat=[ns0.ArrayOfdouble_Def(pname="mmat3d", aname="_mmat3d", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getparammmat3dResponse, encoded="urn:IoSteerWS")

class getmetadataRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
getmetadataRequest.typecode = Struct(pname=("urn:IoSteerWS","getmetadata"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getmetadataRequest, encoded="urn:IoSteerWS")

class getmetadataResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        property -- part property
        """
        self._property =  kw.get("property")
getmetadataResponse.typecode = Struct(pname=("urn:IoSteerWS","getmetadataResponse"), ofwhat=[ZSI.TC.String(pname="property", aname="_property", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getmetadataResponse, encoded="urn:IoSteerWS")

class setparamdoubleRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
setparamdoubleRequest.typecode = Struct(pname=("urn:IoSteerWS","setparamdouble"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.FPdouble(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparamdoubleRequest, encoded="urn:IoSteerWS")

class setparamdoubleResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
setparamdoubleResponse.typecode = Struct(pname=("urn:IoSteerWS","setparamdoubleResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparamdoubleResponse, encoded="urn:IoSteerWS")

class setparamintRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
setparamintRequest.typecode = Struct(pname=("urn:IoSteerWS","setparamint"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparamintRequest, encoded="urn:IoSteerWS")

class setparamintResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
setparamintResponse.typecode = Struct(pname=("urn:IoSteerWS","setparamintResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparamintResponse, encoded="urn:IoSteerWS")

class setparamvecRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        n -- part n
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
        self._n =  kw.get("n")
setparamvecRequest.typecode = Struct(pname=("urn:IoSteerWS","setparamvec"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.ArrayOfdouble_Def(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="n", aname="_n", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparamvecRequest, encoded="urn:IoSteerWS")

class setparamvecResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
setparamvecResponse.typecode = Struct(pname=("urn:IoSteerWS","setparamvecResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparamvecResponse, encoded="urn:IoSteerWS")

class setparammatRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        nr -- part nr
        nc -- part nc
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
        self._nr =  kw.get("nr")
        self._nc =  kw.get("nc")
setparammatRequest.typecode = Struct(pname=("urn:IoSteerWS","setparammat"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.ArrayOfdouble_Def(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nr", aname="_nr", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nc", aname="_nc", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparammatRequest, encoded="urn:IoSteerWS")

class setparammatResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
setparammatResponse.typecode = Struct(pname=("urn:IoSteerWS","setparammatResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparammatResponse, encoded="urn:IoSteerWS")

class setparamstringRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
setparamstringRequest.typecode = Struct(pname=("urn:IoSteerWS","setparamstring"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparamstringRequest, encoded="urn:IoSteerWS")

class setparamstringResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
setparamstringResponse.typecode = Struct(pname=("urn:IoSteerWS","setparamstringResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparamstringResponse, encoded="urn:IoSteerWS")

class setparammmat3dRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        value -- part value
        n -- part n
        p -- part p
        q -- part q
        nr -- part nr
        nc -- part nc
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._value =  kw.get("value")
        self._n =  kw.get("n")
        self._p =  kw.get("p")
        self._q =  kw.get("q")
        self._nr =  kw.get("nr")
        self._nc =  kw.get("nc")
setparammmat3dRequest.typecode = Struct(pname=("urn:IoSteerWS","setparammmat3d"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.ArrayOfdouble_Def(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="n", aname="_n", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="p", aname="_p", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="q", aname="_q", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nr", aname="_nr", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="nc", aname="_nc", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparammmat3dRequest, encoded="urn:IoSteerWS")

class setparammmat3dResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
setparammmat3dResponse.typecode = Struct(pname=("urn:IoSteerWS","setparammmat3dResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setparammmat3dResponse, encoded="urn:IoSteerWS")

class setmetadataRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        name -- part name
        property -- part property
        """
        self._id =  kw.get("id")
        self._name =  kw.get("name")
        self._property =  kw.get("property")
setmetadataRequest.typecode = Struct(pname=("urn:IoSteerWS","setmetadata"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="property", aname="_property", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setmetadataRequest, encoded="urn:IoSteerWS")

class setmetadataResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
setmetadataResponse.typecode = Struct(pname=("urn:IoSteerWS","setmetadataResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setmetadataResponse, encoded="urn:IoSteerWS")

class deleteparamRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        name -- part name
        id -- part id
        """
        self._name =  kw.get("name")
        self._id =  kw.get("id")
deleteparamRequest.typecode = Struct(pname=("urn:IoSteerWS","deleteparam"), ofwhat=[ZSI.TC.String(pname="name", aname="_name", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=deleteparamRequest, encoded="urn:IoSteerWS")

class deleteparamResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        status -- part status
        """
        self._status =  kw.get("status")
deleteparamResponse.typecode = Struct(pname=("urn:IoSteerWS","deleteparamResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="status", aname="_status", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=deleteparamResponse, encoded="urn:IoSteerWS")

class listparamRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        type -- part type
        id -- part id
        """
        self._type =  kw.get("type")
        self._id =  kw.get("id")
listparamRequest.typecode = Struct(pname=("urn:IoSteerWS","listparam"), ofwhat=[ZSI.TC.String(pname="type", aname="_type", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=listparamRequest, encoded="urn:IoSteerWS")

class listparamResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        list -- part list
        """
        self._list =  kw.get("list")
listparamResponse.typecode = Struct(pname=("urn:IoSteerWS","listparamResponse"), ofwhat=[ZSI.TC.String(pname="list", aname="_list", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=listparamResponse, encoded="urn:IoSteerWS")

class getnumobjRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        """
        self._id =  kw.get("id")
getnumobjRequest.typecode = Struct(pname=("urn:IoSteerWS","getnumobj"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getnumobjRequest, encoded="urn:IoSteerWS")

class getnumobjResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        numobj -- part numobj
        """
        self._numobj =  kw.get("numobj")
getnumobjResponse.typecode = Struct(pname=("urn:IoSteerWS","getnumobjResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="numobj", aname="_numobj", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getnumobjResponse, encoded="urn:IoSteerWS")

class getobjnumRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        """
        self._id =  kw.get("id")
getobjnumRequest.typecode = Struct(pname=("urn:IoSteerWS","getobjnum"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getobjnumRequest, encoded="urn:IoSteerWS")

class getobjnumResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        objnum -- part objnum
        """
        self._objnum =  kw.get("objnum")
getobjnumResponse.typecode = Struct(pname=("urn:IoSteerWS","getobjnumResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="objnum", aname="_objnum", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getobjnumResponse, encoded="urn:IoSteerWS")

class testgroupbarrierRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        """
        self._id =  kw.get("id")
testgroupbarrierRequest.typecode = Struct(pname=("urn:IoSteerWS","testgroupbarrier"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=testgroupbarrierRequest, encoded="urn:IoSteerWS")

class testgroupbarrierResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        state -- part state
        """
        self._state =  kw.get("state")
testgroupbarrierResponse.typecode = Struct(pname=("urn:IoSteerWS","testgroupbarrierResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="state", aname="_state", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=testgroupbarrierResponse, encoded="urn:IoSteerWS")

class setgroupbarrierRequest:
    def __init__(self, **kw):
        """Keyword parameters:
        id -- part id
        state -- part state
        """
        self._id =  kw.get("id")
        self._state =  kw.get("state")
setgroupbarrierRequest.typecode = Struct(pname=("urn:IoSteerWS","setgroupbarrier"), ofwhat=[ZSI.TCnumbers.Iint(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iint(pname="state", aname="_state", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setgroupbarrierRequest, encoded="urn:IoSteerWS")

class setgroupbarrierResponse:
    def __init__(self, **kw):
        """Keyword parameters:
        newstate -- part newstate
        """
        self._newstate =  kw.get("newstate")
setgroupbarrierResponse.typecode = Struct(pname=("urn:IoSteerWS","setgroupbarrierResponse"), ofwhat=[ZSI.TCnumbers.Iint(pname="newstate", aname="_newstate", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=setgroupbarrierResponse, encoded="urn:IoSteerWS")


# Service Skeletons
class IoSteerWS(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/IOSteerWS.cgi', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_add(self, ps, **kw):
        request = ps.Parse(addRequest.typecode)
        return request,addResponse()

    soapAction[''] = 'soap_add'
    root[(addRequest.typecode.nspname,addRequest.typecode.pname)] = 'soap_add'

    def soap_getstep(self, ps, **kw):
        request = ps.Parse(getstepRequest.typecode)
        return request,getstepResponse()

    soapAction[''] = 'soap_getstep'
    root[(getstepRequest.typecode.nspname,getstepRequest.typecode.pname)] = 'soap_getstep'

    def soap_setstep(self, ps, **kw):
        request = ps.Parse(setstepRequest.typecode)
        return request,setstepResponse()

    soapAction[''] = 'soap_setstep'
    root[(setstepRequest.typecode.nspname,setstepRequest.typecode.pname)] = 'soap_setstep'

    def soap_getnsteps(self, ps, **kw):
        request = ps.Parse(getnstepsRequest.typecode)
        return request,getnstepsResponse()

    soapAction[''] = 'soap_getnsteps'
    root[(getnstepsRequest.typecode.nspname,getnstepsRequest.typecode.pname)] = 'soap_getnsteps'

    def soap_setnsteps(self, ps, **kw):
        request = ps.Parse(setnstepsRequest.typecode)
        return request,setnstepsResponse()

    soapAction[''] = 'soap_setnsteps'
    root[(setnstepsRequest.typecode.nspname,setnstepsRequest.typecode.pname)] = 'soap_setnsteps'

    def soap_runsimulationstep(self, ps, **kw):
        request = ps.Parse(runsimulationstepRequest.typecode)
        return request,runsimulationstepResponse()

    soapAction[''] = 'soap_runsimulationstep'
    root[(runsimulationstepRequest.typecode.nspname,runsimulationstepRequest.typecode.pname)] = 'soap_runsimulationstep'

    def soap_runsimulation(self, ps, **kw):
        request = ps.Parse(runsimulationRequest.typecode)
        return request,runsimulationResponse()

    soapAction[''] = 'soap_runsimulation'
    root[(runsimulationRequest.typecode.nspname,runsimulationRequest.typecode.pname)] = 'soap_runsimulation'

    def soap_submitsimulation(self, ps, **kw):
        request = ps.Parse(submitsimulationRequest.typecode)
        return request,submitsimulationResponse()

    soapAction[''] = 'soap_submitsimulation'
    root[(submitsimulationRequest.typecode.nspname,submitsimulationRequest.typecode.pname)] = 'soap_submitsimulation'

    def soap_simulationstatus(self, ps, **kw):
        request = ps.Parse(simulationstatusRequest.typecode)
        return request,simulationstatusResponse()

    soapAction[''] = 'soap_simulationstatus'
    root[(simulationstatusRequest.typecode.nspname,simulationstatusRequest.typecode.pname)] = 'soap_simulationstatus'

    def soap_getsimulationresults(self, ps, **kw):
        request = ps.Parse(getsimulationresultsRequest.typecode)
        return request,getsimulationresultsResponse()

    soapAction[''] = 'soap_getsimulationresults'
    root[(getsimulationresultsRequest.typecode.nspname,getsimulationresultsRequest.typecode.pname)] = 'soap_getsimulationresults'

    def soap_deletesimulation(self, ps, **kw):
        request = ps.Parse(deletesimulationRequest.typecode)
        return request,deletesimulationResponse()

    soapAction[''] = 'soap_deletesimulation'
    root[(deletesimulationRequest.typecode.nspname,deletesimulationRequest.typecode.pname)] = 'soap_deletesimulation'

    def soap_newsimulation(self, ps, **kw):
        request = ps.Parse(newsimulationRequest.typecode)
        return request,newsimulationResponse()

    soapAction[''] = 'soap_newsimulation'
    root[(newsimulationRequest.typecode.nspname,newsimulationRequest.typecode.pname)] = 'soap_newsimulation'

    def soap_createsimulation(self, ps, **kw):
        request = ps.Parse(createsimulationRequest.typecode)
        return request,createsimulationResponse()

    soapAction[''] = 'soap_createsimulation'
    root[(createsimulationRequest.typecode.nspname,createsimulationRequest.typecode.pname)] = 'soap_createsimulation'

    def soap_writesimulation(self, ps, **kw):
        request = ps.Parse(writesimulationRequest.typecode)
        return request,writesimulationResponse()

    soapAction[''] = 'soap_writesimulation'
    root[(writesimulationRequest.typecode.nspname,writesimulationRequest.typecode.pname)] = 'soap_writesimulation'

    def soap_readsimulation(self, ps, **kw):
        request = ps.Parse(readsimulationRequest.typecode)
        return request,readsimulationResponse()

    soapAction[''] = 'soap_readsimulation'
    root[(readsimulationRequest.typecode.nspname,readsimulationRequest.typecode.pname)] = 'soap_readsimulation'

    def soap_exitiome(self, ps, **kw):
        request = ps.Parse(exitiomeRequest.typecode)
        return request,exitiomeResponse()

    soapAction[''] = 'soap_exitiome'
    root[(exitiomeRequest.typecode.nspname,exitiomeRequest.typecode.pname)] = 'soap_exitiome'

    def soap_addparamdouble(self, ps, **kw):
        request = ps.Parse(addparamdoubleRequest.typecode)
        return request,addparamdoubleResponse()

    soapAction[''] = 'soap_addparamdouble'
    root[(addparamdoubleRequest.typecode.nspname,addparamdoubleRequest.typecode.pname)] = 'soap_addparamdouble'

    def soap_addparamint(self, ps, **kw):
        request = ps.Parse(addparamintRequest.typecode)
        return request,addparamintResponse()

    soapAction[''] = 'soap_addparamint'
    root[(addparamintRequest.typecode.nspname,addparamintRequest.typecode.pname)] = 'soap_addparamint'

    def soap_addparamvec(self, ps, **kw):
        request = ps.Parse(addparamvecRequest.typecode)
        return request,addparamvecResponse()

    soapAction[''] = 'soap_addparamvec'
    root[(addparamvecRequest.typecode.nspname,addparamvecRequest.typecode.pname)] = 'soap_addparamvec'

    def soap_addparammat(self, ps, **kw):
        request = ps.Parse(addparammatRequest.typecode)
        return request,addparammatResponse()

    soapAction[''] = 'soap_addparammat'
    root[(addparammatRequest.typecode.nspname,addparammatRequest.typecode.pname)] = 'soap_addparammat'

    def soap_addparamstring(self, ps, **kw):
        request = ps.Parse(addparamstringRequest.typecode)
        return request,addparamstringResponse()

    soapAction[''] = 'soap_addparamstring'
    root[(addparamstringRequest.typecode.nspname,addparamstringRequest.typecode.pname)] = 'soap_addparamstring'

    def soap_addparammmat3d(self, ps, **kw):
        request = ps.Parse(addparammmat3dRequest.typecode)
        return request,addparammmat3dResponse()

    soapAction[''] = 'soap_addparammmat3d'
    root[(addparammmat3dRequest.typecode.nspname,addparammmat3dRequest.typecode.pname)] = 'soap_addparammmat3d'

    def soap_addmetadata(self, ps, **kw):
        request = ps.Parse(addmetadataRequest.typecode)
        return request,addmetadataResponse()

    soapAction[''] = 'soap_addmetadata'
    root[(addmetadataRequest.typecode.nspname,addmetadataRequest.typecode.pname)] = 'soap_addmetadata'

    def soap_getparamdouble(self, ps, **kw):
        request = ps.Parse(getparamdoubleRequest.typecode)
        return request,getparamdoubleResponse()

    soapAction[''] = 'soap_getparamdouble'
    root[(getparamdoubleRequest.typecode.nspname,getparamdoubleRequest.typecode.pname)] = 'soap_getparamdouble'

    def soap_getparamint(self, ps, **kw):
        request = ps.Parse(getparamintRequest.typecode)
        return request,getparamintResponse()

    soapAction[''] = 'soap_getparamint'
    root[(getparamintRequest.typecode.nspname,getparamintRequest.typecode.pname)] = 'soap_getparamint'

    def soap_getparamvec(self, ps, **kw):
        request = ps.Parse(getparamvecRequest.typecode)
        return request,getparamvecResponse()

    soapAction[''] = 'soap_getparamvec'
    root[(getparamvecRequest.typecode.nspname,getparamvecRequest.typecode.pname)] = 'soap_getparamvec'

    def soap_getparammat(self, ps, **kw):
        request = ps.Parse(getparammatRequest.typecode)
        return request,getparammatResponse()

    soapAction[''] = 'soap_getparammat'
    root[(getparammatRequest.typecode.nspname,getparammatRequest.typecode.pname)] = 'soap_getparammat'

    def soap_getparamstring(self, ps, **kw):
        request = ps.Parse(getparamstringRequest.typecode)
        return request,getparamstringResponse()

    soapAction[''] = 'soap_getparamstring'
    root[(getparamstringRequest.typecode.nspname,getparamstringRequest.typecode.pname)] = 'soap_getparamstring'

    def soap_getparammmat3d(self, ps, **kw):
        request = ps.Parse(getparammmat3dRequest.typecode)
        return request,getparammmat3dResponse()

    soapAction[''] = 'soap_getparammmat3d'
    root[(getparammmat3dRequest.typecode.nspname,getparammmat3dRequest.typecode.pname)] = 'soap_getparammmat3d'

    def soap_getmetadata(self, ps, **kw):
        request = ps.Parse(getmetadataRequest.typecode)
        return request,getmetadataResponse()

    soapAction[''] = 'soap_getmetadata'
    root[(getmetadataRequest.typecode.nspname,getmetadataRequest.typecode.pname)] = 'soap_getmetadata'

    def soap_setparamdouble(self, ps, **kw):
        request = ps.Parse(setparamdoubleRequest.typecode)
        return request,setparamdoubleResponse()

    soapAction[''] = 'soap_setparamdouble'
    root[(setparamdoubleRequest.typecode.nspname,setparamdoubleRequest.typecode.pname)] = 'soap_setparamdouble'

    def soap_setparamint(self, ps, **kw):
        request = ps.Parse(setparamintRequest.typecode)
        return request,setparamintResponse()

    soapAction[''] = 'soap_setparamint'
    root[(setparamintRequest.typecode.nspname,setparamintRequest.typecode.pname)] = 'soap_setparamint'

    def soap_setparamvec(self, ps, **kw):
        request = ps.Parse(setparamvecRequest.typecode)
        return request,setparamvecResponse()

    soapAction[''] = 'soap_setparamvec'
    root[(setparamvecRequest.typecode.nspname,setparamvecRequest.typecode.pname)] = 'soap_setparamvec'

    def soap_setparammat(self, ps, **kw):
        request = ps.Parse(setparammatRequest.typecode)
        return request,setparammatResponse()

    soapAction[''] = 'soap_setparammat'
    root[(setparammatRequest.typecode.nspname,setparammatRequest.typecode.pname)] = 'soap_setparammat'

    def soap_setparamstring(self, ps, **kw):
        request = ps.Parse(setparamstringRequest.typecode)
        return request,setparamstringResponse()

    soapAction[''] = 'soap_setparamstring'
    root[(setparamstringRequest.typecode.nspname,setparamstringRequest.typecode.pname)] = 'soap_setparamstring'

    def soap_setparammmat3d(self, ps, **kw):
        request = ps.Parse(setparammmat3dRequest.typecode)
        return request,setparammmat3dResponse()

    soapAction[''] = 'soap_setparammmat3d'
    root[(setparammmat3dRequest.typecode.nspname,setparammmat3dRequest.typecode.pname)] = 'soap_setparammmat3d'

    def soap_setmetadata(self, ps, **kw):
        request = ps.Parse(setmetadataRequest.typecode)
        return request,setmetadataResponse()

    soapAction[''] = 'soap_setmetadata'
    root[(setmetadataRequest.typecode.nspname,setmetadataRequest.typecode.pname)] = 'soap_setmetadata'

    def soap_deleteparam(self, ps, **kw):
        request = ps.Parse(deleteparamRequest.typecode)
        return request,deleteparamResponse()

    soapAction[''] = 'soap_deleteparam'
    root[(deleteparamRequest.typecode.nspname,deleteparamRequest.typecode.pname)] = 'soap_deleteparam'

    def soap_listparam(self, ps, **kw):
        request = ps.Parse(listparamRequest.typecode)
        return request,listparamResponse()

    soapAction[''] = 'soap_listparam'
    root[(listparamRequest.typecode.nspname,listparamRequest.typecode.pname)] = 'soap_listparam'

    def soap_getnumobj(self, ps, **kw):
        request = ps.Parse(getnumobjRequest.typecode)
        return request,getnumobjResponse()

    soapAction[''] = 'soap_getnumobj'
    root[(getnumobjRequest.typecode.nspname,getnumobjRequest.typecode.pname)] = 'soap_getnumobj'

    def soap_getobjnum(self, ps, **kw):
        request = ps.Parse(getobjnumRequest.typecode)
        return request,getobjnumResponse()

    soapAction[''] = 'soap_getobjnum'
    root[(getobjnumRequest.typecode.nspname,getobjnumRequest.typecode.pname)] = 'soap_getobjnum'

    def soap_testgroupbarrier(self, ps, **kw):
        request = ps.Parse(testgroupbarrierRequest.typecode)
        return request,testgroupbarrierResponse()

    soapAction[''] = 'soap_testgroupbarrier'
    root[(testgroupbarrierRequest.typecode.nspname,testgroupbarrierRequest.typecode.pname)] = 'soap_testgroupbarrier'

    def soap_setgroupbarrier(self, ps, **kw):
        request = ps.Parse(setgroupbarrierRequest.typecode)
        return request,setgroupbarrierResponse()

    soapAction[''] = 'soap_setgroupbarrier'
    root[(setgroupbarrierRequest.typecode.nspname,setgroupbarrierRequest.typecode.pname)] = 'soap_setgroupbarrier'

