#!/bin/bash
#
# This is an example script for submitting mpi parallel jobs
# 
# Use this script as a template for your mpi jobs 
#$ -l h_rt=1:00:00
#$ -j y
#$ -pe openmpi-ib 4 

 
# 

module load  mpi/intel/openmpi/1.8.3

 mpirun ./diffuse  < testmpi.dat
