function dval = getparammat(obj,id,name,nr,nc)
%getparammat(obj,id,name,nr,nc)
%
%   Service definition of function ns__getparammat
%   
%     Input:
%       id = (int)
%       name = (string)
%       nr = (int)
%       nc = (int)
%   
%     Output:
%       dval = (Array)

% Build up the argument lists.
values = { ...
   id, ...
   name, ...
   nr, ...
   nc, ...
   };
names = { ...
   'id', ...
   'name', ...
   'nr', ...
   'nc', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'getparammat', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
dval = parseSoapResponse(response);
